package archtest

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGeneratedRequiresCanonicalGoMarker(t *testing.T) {
	tests := []struct {
		name     string
		contents string
		want     bool
	}{
		{
			name: "canonical marker",
			contents: `// Code generated by hardening test. DO NOT EDIT.
package generated
`,
			want: true,
		},
		{
			name: "canonical marker after leading comments",
			contents: `// Copyright Loom contributors.
//
// License text.
// Code generated by hardening test. DO NOT EDIT.
package generated
`,
			want: true,
		},
		{
			name: "missing canonical suffix",
			contents: `// Code generated by hardening test.
package handwritten
`,
		},
		{
			name: "canonical text embedded in another comment",
			contents: `// Prefix: // Code generated by hardening test. DO NOT EDIT.
package handwritten
`,
		},
		{
			name: "text after canonical suffix",
			contents: `// Code generated by hardening test. DO NOT EDIT. Extra text.
package handwritten
`,
		},
		{
			name: "canonical marker after package declaration",
			contents: `package handwritten
// Code generated by hardening test. DO NOT EDIT.
`,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if got := generated([]byte(test.contents)); got != test.want {
				t.Fatalf("generated() = %t, want %t", got, test.want)
			}
		})
	}
}

func TestGeneratedMarkerPolicyAppliesToAnalyzerAndRuntimeScans(t *testing.T) {
	root := t.TempDir()
	writeHardeningGoFile(t, root, "internal/spoof/spoof.go", `// Code generated by a spoof marker without the canonical suffix.
package spoof

import (
	"time"

	"github.com/tysonthomas9/loomcli/internal/store"
)

func Run() {
	_ = store.Store{}
	_ = time.NewTicker(time.Second)
	go func() {}()
}
`)
	writeHardeningGoFile(t, root, "internal/canonical/canonical.go", `// Copyright Loom contributors.
//
// The canonical marker may follow other leading comments.
// Code generated by hardening test. DO NOT EDIT.
package canonical

import (
	"time"

	"github.com/tysonthomas9/loomcli/internal/store"
)

func Run() {
	_ = store.Store{}
	_ = time.NewTicker(time.Second)
	go func() {}()
}
`)

	compositeFiles, err := findCompositeStoreFiles(root)
	if err != nil {
		t.Fatal(err)
	}
	if got, want := strings.Join(compositeFiles, ","), "internal/spoof/spoof.go"; got != want {
		t.Fatalf("composite Store files = %q, want %q", got, want)
	}

	tickerSites, err := ScanProductionTickerSites(root, validRuntimeInventory())
	if err != nil {
		t.Fatal(err)
	}
	if len(tickerSites) != 1 || tickerSites[0].File != "internal/spoof/spoof.go" {
		t.Fatalf("ticker sites = %+v, want only the spoof-marked file", tickerSites)
	}

	goroutineSites, err := ScanProductionGoroutineSites(root, validRuntimeInventory())
	if err != nil {
		t.Fatal(err)
	}
	if len(goroutineSites) != 1 || goroutineSites[0].File != "internal/spoof/spoof.go" {
		t.Fatalf("goroutine sites = %+v, want only the spoof-marked file", goroutineSites)
	}
}

func TestLoadDirectWritePackagesFailsClosedForUnavailableAdapterRoot(t *testing.T) {
	tests := []struct {
		name        string
		adapterRoot string
		setup       func(*testing.T, string)
	}{
		{
			name:        "missing root",
			adapterRoot: "internal/missing",
			setup:       func(*testing.T, string) {},
		},
		{
			name:        "stat error",
			adapterRoot: "internal/not-a-directory/adapter",
			setup: func(t *testing.T, root string) {
				t.Helper()
				path := filepath.Join(root, "internal", "not-a-directory")
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(path, []byte("obstruction"), 0o600); err != nil {
					t.Fatal(err)
				}
			},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			test.setup(t, root)

			loaded, err := loadDirectWritePackages(
				root,
				AnalysisProfile{Name: "hardening"},
				[]string{test.adapterRoot},
			)
			if err == nil {
				t.Fatalf("loadDirectWritePackages() = (%v, nil), want adapter-root error", loaded)
			}
			want := `inspect direct-write adapter root "` + test.adapterRoot + `"`
			if !strings.Contains(err.Error(), want) {
				t.Fatalf("loadDirectWritePackages() error = %q, want %q", err, want)
			}
		})
	}
}

func writeHardeningGoFile(t *testing.T, root, relativePath, contents string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(relativePath))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}
}
