package archtest

import (
	"bytes"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestCheckedInProductionPackageShape(t *testing.T) {
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	inventory, err := LoadProductionPackageShapeInventory(filepath.Join("testdata", "production-package-shape.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if err := CompareProductionPackageShape(root, inventory); err != nil {
		t.Fatal(err)
	}
}

func TestScanProductionPackageShapeUsesPackageTopologySemantics(t *testing.T) {
	root := t.TempDir()
	writeGoFile(t, root, "internal/handwritten/handwritten.go", "package handwritten\n")
	writeGoFile(t, root, "internal/handwritten/handwritten_test.go", "package handwritten\n")
	writeGoFile(t, root, "internal/testonly/testonly_test.go", "package testonly\n")
	writeGoFile(t, root, "internal/generated/generated.go", `// Code generated by package-shape test. DO NOT EDIT.
package generated
`)
	writeGoFile(t, root, "internal/modules/workitems/workitems_linux.go", `//go:build linux

package workitems
`)
	writeGoFile(t, root, "internal/vendor/hidden/hidden.go", "package hidden\n")

	shape, err := ScanProductionPackageShape(root, packageShapeTestSemantics())
	if err != nil {
		t.Fatal(err)
	}
	wantPackages := []string{
		"internal/generated",
		"internal/handwritten",
		"internal/modules/workitems",
	}
	if !slices.Equal(shape.Packages, wantPackages) {
		t.Fatalf("packages = %v, want %v", shape.Packages, wantPackages)
	}
	if shape.TotalPackages != 3 || shape.ModulePackages != 1 || shape.OutsideModulePackages != 2 {
		t.Fatalf("package partition = total %d, modules %d, outside %d; want 3/1/2", shape.TotalPackages, shape.ModulePackages, shape.OutsideModulePackages)
	}
	if shape.OneFilePackages != 3 || shape.OneOrTwoFilePackages != 3 {
		t.Fatalf("small-package counts = one %d, one-or-two %d; want 3/3", shape.OneFilePackages, shape.OneOrTwoFilePackages)
	}
}

func TestCompareProductionPackageShapeRejectsInventoryDrift(t *testing.T) {
	t.Run("count-neutral replacement", func(t *testing.T) {
		root := t.TempDir()
		writeGoFile(t, root, "internal/replacement/replacement.go", "package replacement\n")
		inventory := packageShapeTestInventory([]string{"internal/approved"}, ProductionPackageShapeCeilings{
			TotalPackages: 1, OutsideModulePackages: 1, OneFilePackages: 1, OneOrTwoFilePackages: 1,
		})

		err := CompareProductionPackageShape(root, inventory)
		for _, want := range []string{
			"unapproved production package internal/replacement",
			"stale/deleted production package inventory entry internal/approved",
		} {
			if err == nil || !strings.Contains(err.Error(), want) {
				t.Fatalf("CompareProductionPackageShape error = %v, want %q", err, want)
			}
		}
	})

	t.Run("unapproved package", func(t *testing.T) {
		root := t.TempDir()
		writeGoFile(t, root, "internal/approved/approved.go", "package approved\n")
		inventory := packageShapeTestInventory([]string{"internal/approved"}, ProductionPackageShapeCeilings{
			TotalPackages: 1, OutsideModulePackages: 1, OneFilePackages: 1, OneOrTwoFilePackages: 1,
		})
		writeGoFile(t, root, "internal/newboundary/newboundary.go", "package newboundary\n")

		err := CompareProductionPackageShape(root, inventory)
		for _, want := range []string{"unapproved production package internal/newboundary", "total package directories = 2 exceeds ceiling 1"} {
			if err == nil || !strings.Contains(err.Error(), want) {
				t.Fatalf("CompareProductionPackageShape error = %v, want %q", err, want)
			}
		}
	})

	t.Run("stale deleted package", func(t *testing.T) {
		root := t.TempDir()
		writeGoFile(t, root, "internal/present/present.go", "package present\n")
		inventory := packageShapeTestInventory([]string{"internal/deleted", "internal/present"}, ProductionPackageShapeCeilings{
			TotalPackages: 2, OutsideModulePackages: 2, OneFilePackages: 2, OneOrTwoFilePackages: 2,
		})

		err := CompareProductionPackageShape(root, inventory)
		if err == nil || !strings.Contains(err.Error(), "stale/deleted production package inventory entry internal/deleted") {
			t.Fatalf("CompareProductionPackageShape error = %v, want stale/deleted inventory rejection", err)
		}
	})
}

func TestProductionPackageShapeCeilingsRejectEveryIncrease(t *testing.T) {
	ceilings := ProductionPackageShapeCeilings{
		TotalPackages:         3,
		ModulePackages:        1,
		OutsideModulePackages: 2,
		OneFilePackages:       1,
		OneOrTwoFilePackages:  2,
	}
	tests := []struct {
		name   string
		mutate func(*ProductionPackageShape)
		want   string
	}{
		{name: "total", mutate: func(shape *ProductionPackageShape) { shape.TotalPackages++ }, want: "total package directories"},
		{name: "modules", mutate: func(shape *ProductionPackageShape) { shape.ModulePackages++ }, want: "packages under internal/modules"},
		{name: "outside modules", mutate: func(shape *ProductionPackageShape) { shape.OutsideModulePackages++ }, want: "packages outside internal/modules"},
		{name: "one file", mutate: func(shape *ProductionPackageShape) { shape.OneFilePackages++ }, want: "one-file package directories"},
		{name: "one or two files", mutate: func(shape *ProductionPackageShape) { shape.OneOrTwoFilePackages++ }, want: "one-or-two-file package directories"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			shape := ProductionPackageShape{
				TotalPackages:         ceilings.TotalPackages,
				ModulePackages:        ceilings.ModulePackages,
				OutsideModulePackages: ceilings.OutsideModulePackages,
				OneFilePackages:       ceilings.OneFilePackages,
				OneOrTwoFilePackages:  ceilings.OneOrTwoFilePackages,
			}
			test.mutate(&shape)
			violations := productionPackageShapeCeilingViolations(shape, ceilings)
			if !slices.ContainsFunc(violations, func(value string) bool { return strings.Contains(value, test.want) }) {
				t.Fatalf("ceiling violations = %v, want entry containing %q", violations, test.want)
			}
		})
	}
}

func TestProductionPackageShapeInventoryPinsScanSemantics(t *testing.T) {
	inventory := packageShapeTestInventory([]string{"internal/example"}, ProductionPackageShapeCeilings{
		TotalPackages: 1, OutsideModulePackages: 1, OneFilePackages: 1, OneOrTwoFilePackages: 1,
	})

	inventory.Semantics.ExcludeTestFiles = false
	if err := inventory.Validate(); err == nil || !strings.Contains(err.Error(), "must exclude _test.go") {
		t.Fatalf("Validate error = %v, want test-file policy rejection", err)
	}
	inventory.Semantics = packageShapeTestSemantics()
	inventory.Semantics.GeneratedFiles = "exclude"
	if err := inventory.Validate(); err == nil || !strings.Contains(err.Error(), packageShapeGeneratedFilesPolicy) {
		t.Fatalf("Validate error = %v, want generated-file topology policy rejection", err)
	}
	inventory.Semantics = packageShapeTestSemantics()
	inventory.Packages = []string{"internal/z", "internal/a"}
	inventory.Ceilings.TotalPackages = 2
	inventory.Ceilings.OutsideModulePackages = 2
	if err := inventory.Validate(); err == nil || !strings.Contains(err.Error(), "must be sorted") {
		t.Fatalf("Validate error = %v, want sorted inventory rejection", err)
	}
}

func TestRebaselineProductionPackageShapeOnlyTightens(t *testing.T) {
	inventory := packageShapeTestInventory([]string{"internal/a", "internal/b"}, ProductionPackageShapeCeilings{
		TotalPackages: 2, OutsideModulePackages: 2, OneFilePackages: 2, OneOrTwoFilePackages: 2,
	})
	observed := ProductionPackageShape{
		Packages:              []string{"internal/a"},
		TotalPackages:         1,
		OutsideModulePackages: 1,
		OneFilePackages:       1,
		OneOrTwoFilePackages:  1,
	}
	refreshed, err := rebaselineProductionPackageShape(inventory, observed)
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(refreshed.Packages, observed.Packages) || refreshed.Ceilings.TotalPackages != 1 || refreshed.Ceilings.OneFilePackages != 1 {
		t.Fatalf("refreshed inventory = %+v, want observed one-package shape", refreshed)
	}

	withAddition := observed
	withAddition.Packages = []string{"internal/a", "internal/new"}
	withAddition.TotalPackages = 2
	withAddition.OutsideModulePackages = 2
	withAddition.OneFilePackages = 2
	withAddition.OneOrTwoFilePackages = 2
	if _, err := rebaselineProductionPackageShape(inventory, withAddition); err == nil || !strings.Contains(err.Error(), "refuse to approve new production packages") {
		t.Fatalf("rebaseline error = %v, want new-package refusal", err)
	}

	withIncrease := observed
	withIncrease.OneFilePackages = 3
	withIncrease.OneOrTwoFilePackages = 3
	if _, err := rebaselineProductionPackageShape(inventory, withIncrease); err == nil || !strings.Contains(err.Error(), "refuse to raise") {
		t.Fatalf("rebaseline error = %v, want ceiling-increase refusal", err)
	}
}

// TestRegenerateProductionPackageShapeInventory is an explicit, mechanical
// refresh path for reviewed consolidation changes. It never writes during an
// ordinary test run. Run:
//
//	LOOM_UPDATE_PACKAGE_SHAPE=1 go test ./internal/archtest \
//	  -run TestRegenerateProductionPackageShapeInventory -count=1
//
// The refresh lowers every ceiling to the currently observed shape and removes
// stale package approvals; review the resulting inventory as architecture.
func TestRegenerateProductionPackageShapeInventory(t *testing.T) {
	if os.Getenv("LOOM_UPDATE_PACKAGE_SHAPE") != "1" {
		t.Skip("set LOOM_UPDATE_PACKAGE_SHAPE=1 for an intentional baseline refresh")
	}
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join("testdata", "production-package-shape.yaml")
	inventory, err := LoadProductionPackageShapeInventory(path)
	if err != nil {
		t.Fatal(err)
	}
	shape, err := ScanProductionPackageShape(root, inventory.Semantics)
	if err != nil {
		t.Fatal(err)
	}
	inventory, err = rebaselineProductionPackageShape(inventory, shape)
	if err != nil {
		t.Fatal(err)
	}
	var encoded bytes.Buffer
	encoder := yaml.NewEncoder(&encoded)
	encoder.SetIndent(2)
	if err := encoder.Encode(inventory); err != nil {
		t.Fatal(err)
	}
	if err := encoder.Close(); err != nil {
		t.Fatal(err)
	}
	header := "# Exact current production-package topology ratchet.\n" +
		"# Generated .go files count as compiled package topology; _test.go files do not.\n" +
		"# Refresh only after an intentional consolidation review; see package_shape_test.go.\n"
	if err := os.WriteFile(path, append([]byte(header), encoded.Bytes()...), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := LoadProductionPackageShapeInventory(path); err != nil {
		t.Fatalf("load refreshed inventory: %v", err)
	}
}

func packageShapeTestSemantics() ProductionPackageShapeSemantics {
	return ProductionPackageShapeSemantics{
		Root:                packageShapeRoot,
		ExcludeTestFiles:    true,
		GeneratedFiles:      packageShapeGeneratedFilesPolicy,
		ExcludedDirectories: append([]string(nil), packageShapeExcludedDirectories...),
	}
}

func packageShapeTestInventory(packages []string, ceilings ProductionPackageShapeCeilings) ProductionPackageShapeInventory {
	return ProductionPackageShapeInventory{
		SchemaVersion: productionPackageShapeSchemaVersion,
		Semantics:     packageShapeTestSemantics(),
		Ceilings:      ceilings,
		Packages:      packages,
	}
}
