// Code generated by the FleetDB action contract generator; DO NOT EDIT.
// FleetDB revision: 000793b28a475366ecaaebe7442a41fbd2ca1710

package fleet

type fleetActionContractRow struct {
	Action             string
	EntityType         string
	ExpectedCoarseType string
}

var fleetActionContract = []fleetActionContractRow{
	{Action: "agent.create", EntityType: "agent", ExpectedCoarseType: "update"},
	{Action: "agent.delete", EntityType: "agent", ExpectedCoarseType: "update"},
	{Action: "agent.update", EntityType: "agent", ExpectedCoarseType: "update"},
	{Action: "comment.add", EntityType: "comment", ExpectedCoarseType: "comment"},
	{Action: "daemon.update", EntityType: "daemon_profile", ExpectedCoarseType: "update"},
	{Action: "dep.add", EntityType: "dependency", ExpectedCoarseType: "update"},
	{Action: "dep.remove", EntityType: "dependency", ExpectedCoarseType: "update"},
	{Action: "driver_run.claim", EntityType: "driver_run", ExpectedCoarseType: "update"},
	{Action: "driver_run.create", EntityType: "driver_run", ExpectedCoarseType: "update"},
	{Action: "driver_run.finish", EntityType: "driver_run", ExpectedCoarseType: "update"},
	{Action: "driver_run.heartbeat", EntityType: "driver_run", ExpectedCoarseType: "update"},
	{Action: "driver_run.recover", EntityType: "driver_run", ExpectedCoarseType: "update"},
	{Action: "driver_run.resume", EntityType: "driver_run", ExpectedCoarseType: "update"},
	{Action: "driver_run.suspend", EntityType: "driver_run", ExpectedCoarseType: "update"},
	{Action: "issue.assign", EntityType: "issue", ExpectedCoarseType: "update"},
	{Action: "issue.claim", EntityType: "issue", ExpectedCoarseType: "update"},
	{Action: "issue.close", EntityType: "issue", ExpectedCoarseType: "status"},
	{Action: "issue.create", EntityType: "issue", ExpectedCoarseType: "create"},
	{Action: "issue.defer", EntityType: "issue", ExpectedCoarseType: "update"},
	{Action: "issue.delete", EntityType: "issue", ExpectedCoarseType: "delete"},
	{Action: "issue.release", EntityType: "issue", ExpectedCoarseType: "update"},
	{Action: "issue.reopen", EntityType: "issue", ExpectedCoarseType: "status"},
	{Action: "issue.undefer", EntityType: "issue", ExpectedCoarseType: "update"},
	{Action: "issue.update", EntityType: "issue", ExpectedCoarseType: "update"},
	{Action: "label.add", EntityType: "label", ExpectedCoarseType: "update"},
	{Action: "label.remove", EntityType: "label", ExpectedCoarseType: "update"},
	{Action: "metadata.remove", EntityType: "metadata", ExpectedCoarseType: "update"},
	{Action: "metadata.set", EntityType: "metadata", ExpectedCoarseType: "update"},
	{Action: "repo.create", EntityType: "repo", ExpectedCoarseType: "update"},
	{Action: "repo.delete", EntityType: "repo", ExpectedCoarseType: "update"},
	{Action: "repo.update", EntityType: "repo", ExpectedCoarseType: "update"},
	{Action: "role.create", EntityType: "role", ExpectedCoarseType: "update"},
	{Action: "role.delete", EntityType: "role", ExpectedCoarseType: "update"},
	{Action: "role.update", EntityType: "role", ExpectedCoarseType: "update"},
	{Action: "skill.create", EntityType: "skill", ExpectedCoarseType: "update"},
	{Action: "skill.delete", EntityType: "skill", ExpectedCoarseType: "update"},
	{Action: "skill.update", EntityType: "skill", ExpectedCoarseType: "update"},
	{Action: "skill_pack.create", EntityType: "skill_pack", ExpectedCoarseType: "update"},
	{Action: "skill_pack.delete", EntityType: "skill_pack", ExpectedCoarseType: "update"},
	{Action: "skill_pack.update", EntityType: "skill_pack", ExpectedCoarseType: "update"},
	{Action: "workspace.create", EntityType: "workspace", ExpectedCoarseType: "refresh"},
	{Action: "workspace.delete", EntityType: "workspace", ExpectedCoarseType: "refresh"},
	{Action: "workspace.update", EntityType: "workspace", ExpectedCoarseType: "refresh"},
}
