package fleet

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
)

// This fixture is generated by Fleet's actual FormatTimeline and v6 HTTP DTO.
func TestRecoveryTimelineFleetProducerFixture(t *testing.T) {
	raw, err := os.ReadFile("testdata/issue_recovery_timeline.json")
	require.NoError(t, err)
	var history recoveryHistoryWire
	require.NoError(t, json.Unmarshal(raw, &history))
	require.NoError(t, validateRecoveryHistory(raw, "WS", map[string]map[string]json.RawMessage{history.IssueID: {}}))
	require.Len(t, *history.Events, len(fleetActionContract)+3)
}
