package driver

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	RuntimeFlueNode = "flue-node"
	EntrypointRun   = "run"
)

type Bundle struct {
	Root         string            `json:"root"`
	BundleRef    string            `json:"bundle_ref"`
	SourceRef    string            `json:"source_ref"`
	SourceDigest string            `json:"source_digest"`
	BundleDigest string            `json:"bundle_digest"`
	Manifest     map[string]string `json:"manifest"`
	Diagnostics  string            `json:"diagnostics,omitempty"`
}

func digestBundleTree(bundleRoot string, manifest []byte) (string, error) {
	h := sha256.New()
	_, _ = h.Write([]byte("loom-driver-bundle-v2\nmanifest\n"))
	_, _ = h.Write(manifest)
	_, _ = h.Write([]byte("\nfiles\n"))
	paths := []string{}
	for _, root := range []string{"dist"} {
		err := filepath.WalkDir(filepath.Join(bundleRoot, filepath.FromSlash(root)), func(path string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				return nil
			}
			rel, err := filepath.Rel(bundleRoot, path)
			if err != nil {
				return err
			}
			paths = append(paths, filepath.ToSlash(rel))
			return nil
		})
		if err != nil {
			if errors.Is(err, fs.ErrNotExist) {
				continue
			}
			return "", fmt.Errorf("digest bundle tree: %w", err)
		}
	}
	sort.Strings(paths)
	for _, rel := range paths {
		data, err := os.ReadFile(filepath.Join(bundleRoot, filepath.FromSlash(rel))) //nolint:gosec // rel is generated by WalkDir under bundleRoot.
		if err != nil {
			return "", fmt.Errorf("digest bundle file %s: %w", rel, err)
		}
		_, _ = h.Write([]byte("file\n"))
		_, _ = h.Write([]byte(rel))
		_, _ = h.Write([]byte("\n"))
		_, _ = h.Write(data)
		_, _ = h.Write([]byte("\n"))
	}
	return "sha256:" + hex.EncodeToString(h.Sum(nil)), nil
}

func digestBytes(data []byte) string {
	sum := sha256.Sum256(data)
	return "sha256:" + hex.EncodeToString(sum[:])
}

func digestShort(digest string) string {
	digest = strings.TrimPrefix(digest, "sha256:")
	if len(digest) > 12 {
		return digest[:12]
	}
	return digest
}

func slug(name string) string {
	name = strings.ToLower(strings.TrimSpace(name))
	var b strings.Builder
	lastDash := false
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastDash = false
		case r == '-' || r == '_' || r == ' ' || r == '.':
			if !lastDash && b.Len() > 0 {
				b.WriteByte('-')
				lastDash = true
			}
		}
	}
	return strings.Trim(b.String(), "-")
}
