import { randomUUID } from 'node:crypto';
import { Id, requireFact } from './protocol.js';
import type { OwnedFixture } from './ownership.js';

/** Only this harmless, generated probe may be counted before redaction. Real
 * credentials and the fixture's secret set are never hashed or counted. */
export interface SyntheticProbe { readonly handle: string; readonly runId: string; readonly leaseId: string; readonly value: string }
const generated = new WeakSet<object>();
export function createSyntheticProbe(runId: string, leaseId: string): SyntheticProbe {
  requireFact(/^[A-Za-z0-9_-]{1,128}$/.test(runId), 'ownership-mismatch', 'Synthetic probe run identity is invalid');
  Id.parse(leaseId);
  const probe = Object.freeze({ leaseId, handle: `redaction-probe-${randomUUID()}`, runId,
    value: `ghp_AFTONLY${runId}Q7mR2pK9xT4vN8cY6bL5fS3dH1jW0` });
  generated.add(probe); return probe;
}
export function getSyntheticProbe(fixture: OwnedFixture, handle: string): SyntheticProbe {
  Id.parse(handle);
  const probe = fixture.syntheticProbe;
  requireFact(probe && generated.has(probe) && probe.runId === fixture.runId && probe.leaseId === fixture.leaseId && probe.handle === handle,
    'ownership-mismatch', 'Synthetic probe is missing or belongs to another fixture');
  return probe;
}
export function probeOccurrences(serialized: string, probe: SyntheticProbe): number {
  requireFact(generated.has(probe), 'ownership-mismatch', 'Synthetic probe was not generated by owned code');
  let count = 0; let after = 0;
  for (;;) {
    const at = serialized.indexOf(probe.value, after);
    if (at < 0) return count;
    count++; after = at + probe.value.length;
  }
}
