package lead

import (
	"context"
	"log/slog"
	"os"
	"path/filepath"

	"github.com/tysonthomas9/loomcli/internal/bootstrap"
	"github.com/tysonthomas9/loomcli/internal/cli/agent"
	"github.com/tysonthomas9/loomcli/internal/localworkspace"
)

// leadAgentsFileName is the ambient-instruction file codex reads from its
// working directory.
//
// There is deliberately no CLAUDE.md counterpart here. claude sessions run
// under their own CLAUDE_CONFIG_DIR (PUPPET-96), which relocates where claude
// reads its ambient instructions from cwd to the profile root - so a CLAUDE.md
// seeded into this directory would be dead weight. claude gets the same persona
// from the profile's own CLAUDE.md, pointed at by `--prompt builtin:lead-profile`
// and generated by `loom lead --print-prompt`.
const leadAgentsFileName = "AGENTS.md"

// resolveLeadWorkdir picks the directory `loom lead` runs in, and reports
// whether that directory is DEDICATED to lead.
//
// Dedicated means the path came from LOOM_LEAD_WORKDIR or from
// <workspacePath>/lead - somewhere lead owns. The fallback, os.Getwd, is
// whatever directory the operator happened to be standing in, and is reported
// as not dedicated: seeding files there or shrinking the argv prompt would be
// actively harmful (see leadSeedAndShrink).
//
// A dedicated directory is created if absent. If creating it fails, the
// fallback applies rather than the launch: `loom lead` must always run.
func resolveLeadWorkdir(ctx context.Context) (string, bool, error) {
	wsKey, err := bootstrap.ResolveActiveWorkspaceKey(ctx, nil)
	if err != nil {
		wsKey = ""
	}
	if dir, ok := localworkspace.EnsureLeadWorkdir(wsKey); ok {
		return dir, true, nil
	}
	cwd, err := os.Getwd()
	if err != nil {
		return "", false, err
	}
	return cwd, false, nil
}

// seedLeadWorkdirFiles writes AGENTS.md into a dedicated lead workdir when it
// is absent, and NEVER overwrites it.
//
// That contract is what makes the file genuinely operator-editable: tuning
// lead's persona in <ws>/lead/AGENTS.md survives every upgrade, and adopting a
// newer shipped default is an explicit operator act (delete the file and
// relaunch). Seeding is best-effort - a failure is logged and lead still runs,
// it just keeps whatever prompt it was given on argv.
func seedLeadWorkdirFiles(workDir string) {
	seedLeadWorkdirFile(filepath.Join(workDir, leadAgentsFileName), agent.LeadAgentsFileText())
}

func seedLeadWorkdirFile(path, content string) {
	_, err := os.Stat(path)
	if err == nil {
		return // already present - leave the operator's copy alone
	}
	if !os.IsNotExist(err) {
		slog.Warn("lead workdir: stat failed, not seeding", "path", path, "err", err)
		return
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		slog.Warn("lead workdir: seed failed", "path", path, "err", err)
	}
}
