//go:build ignore

// gen writes protocol.go from the pinned schema files in schema/. It maps the
// JSON-schema shapes codex uses: objects become structs, string enums become
// string types with constants, unions become json.RawMessage, and other
// named schemas become aliases.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
)

type schema map[string]any

var defs = map[string]schema{}

func main() {
	err := filepath.WalkDir("schema", func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		b, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		var s schema
		if err := json.Unmarshal(b, &s); err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		inner, _ := s["definitions"].(map[string]any)
		delete(s, "definitions")
		delete(s, "$schema")
		if err := define(s["title"].(string), s); err != nil {
			return err
		}
		for name, v := range inner {
			if err := define(name, v.(map[string]any)); err != nil {
				return err
			}
		}
		return nil
	})
	if err == nil {
		err = write()
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen:", err)
		os.Exit(1)
	}
}

// define records a named schema; one name must mean one shape in every file.
func define(name string, s schema) error {
	s = without(s, "title")
	if old, ok := defs[name]; ok && !reflect.DeepEqual(without(old, "description"), without(s, "description")) {
		return fmt.Errorf("%s has two different shapes", name)
	}
	if _, ok := defs[name]; !ok || s["description"] != nil {
		defs[name] = s
	}
	return nil
}

func without(s schema, key string) schema {
	out := schema{}
	for k, v := range s {
		if k != key {
			out[k] = v
		}
	}
	return out
}

func write() error {
	var b bytes.Buffer
	b.WriteString("// Code generated by gen.go from schema/; DO NOT EDIT.\n\npackage protocol\n\nimport \"encoding/json\"\n\n")
	names := make([]string, 0, len(defs))
	for n := range defs {
		names = append(names, n)
	}
	slices.Sort(names)
	for _, n := range names {
		decl(&b, n, defs[n])
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("format: %w\n%s", err, b.Bytes())
	}
	return os.WriteFile("protocol.go", src, 0o644)
}

func decl(b *bytes.Buffer, name string, s schema) {
	comment(b, s)
	props, _ := s["properties"].(map[string]any)
	enum, _ := s["enum"].([]any)
	switch {
	case props != nil:
		fmt.Fprintf(b, "type %s struct {\n", name)
		required, _ := s["required"].([]any)
		keys := make([]string, 0, len(props))
		for k := range props {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		for _, k := range keys {
			p, _ := props[k].(map[string]any)
			req := slices.Contains(required, any(k))
			tag := k
			if !req {
				tag += ",omitempty"
			}
			comment(b, p)
			field := strings.TrimLeft(k, "_$") // "_meta" -> "Meta"
			fmt.Fprintf(b, "%s %s `json:%q`\n", strings.ToUpper(field[:1])+field[1:], goType(props[k], req), tag)
		}
		b.WriteString("}\n\n")
	case enum != nil && s["type"] == "string":
		fmt.Fprintf(b, "type %s string\n\nconst (\n", name)
		for _, v := range enum {
			fmt.Fprintf(b, "%s%s %s = %q\n", name, ident(v.(string)), name, v)
		}
		b.WriteString(")\n\n")
	default:
		fmt.Fprintf(b, "type %s = %s\n\n", name, goType(map[string]any(s), true))
	}
}

func comment(b *bytes.Buffer, s map[string]any) {
	if d, ok := s["description"].(string); ok {
		for _, line := range strings.Split(d, "\n") {
			fmt.Fprintln(b, strings.TrimRight("// "+line, " "))
		}
	}
}

// goType is the Go type of a property schema; optional scalars and structs
// become pointers when null is allowed or the field is optional.
func goType(v any, required bool) string {
	s, ok := v.(map[string]any)
	if !ok {
		return "json.RawMessage" // `true`: any JSON value
	}
	if ref, ok := s["$ref"].(string); ok {
		name := strings.TrimPrefix(ref, "#/definitions/")
		if _, isStruct := defs[name]["properties"]; isStruct && !required {
			return "*" + name
		}
		return name
	}
	if all, ok := s["allOf"].([]any); ok && len(all) == 1 {
		return goType(all[0], required)
	}
	for _, key := range []string{"anyOf", "oneOf"} {
		if alts, ok := s[key].([]any); ok {
			if len(alts) == 2 && isNull(alts[1]) {
				return goType(alts[0], false)
			}
			return "json.RawMessage"
		}
	}
	typ, nullable := s["type"], false
	if list, ok := typ.([]any); ok && len(list) == 2 && list[1] == "null" {
		typ, nullable = list[0], true
	}
	var t string
	switch typ {
	case "string":
		t = "string"
	case "integer":
		t = "int64"
	case "number":
		t = "float64"
	case "boolean":
		t = "bool"
	case "array":
		return "[]" + goType(s["items"], true)
	case "object":
		if add, ok := s["additionalProperties"].(map[string]any); ok {
			return "map[string]" + goType(add, true)
		}
		return "json.RawMessage"
	default:
		return "json.RawMessage"
	}
	if nullable {
		return "*" + t
	}
	return t
}

func isNull(v any) bool {
	s, ok := v.(map[string]any)
	return ok && s["type"] == "null"
}

// ident turns an enum value such as "on-request" into "OnRequest".
func ident(v string) string {
	var b strings.Builder
	for _, part := range strings.FieldsFunc(v, func(r rune) bool { return !('a' <= r && r <= 'z' || 'A' <= r && r <= 'Z' || '0' <= r && r <= '9') }) {
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}
