// Code generated by gen.go from schema/; DO NOT EDIT.

package protocol

import "encoding/json"

// A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).
//
// IMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.
type AbsolutePathBuf = string

type ClientInfo struct {
	Name    string  `json:"name"`
	Title   *string `json:"title,omitempty"`
	Version string  `json:"version"`
}

// Client-declared capabilities negotiated during initialize.
type InitializeCapabilities struct {
	// Opt into receiving experimental API methods and fields.
	ExperimentalApi bool `json:"experimentalApi,omitempty"`
	// Use explicit gateway OAuth login instead of automatic browser authorization. Applies to this app-server's gateway runtime; later connections cannot undo it.
	ExplicitGatewayOauth bool `json:"explicitGatewayOauth,omitempty"`
	// MCP extension settings declared by the app-server client.
	Extensions json.RawMessage `json:"extensions,omitempty"`
	// Legacy opt-in for the `openai/form` MCP extension.
	//
	// New clients should declare `openai/form` in [`Self::extensions`].
	McpServerOpenaiFormElicitation bool `json:"mcpServerOpenaiFormElicitation,omitempty"`
	// Exact notification method names that should be suppressed for this connection (for example `thread/started`).
	OptOutNotificationMethods []string `json:"optOutNotificationMethods,omitempty"`
	// Opt into `attestation/generate` requests for upstream `x-oai-attestation`.
	RequestAttestation bool `json:"requestAttestation,omitempty"`
}

type InitializeParams struct {
	Capabilities *InitializeCapabilities `json:"capabilities,omitempty"`
	ClientInfo   ClientInfo              `json:"clientInfo"`
}

type InitializeResponse struct {
	// Absolute path to the server's $CODEX_HOME directory.
	CodexHome AbsolutePathBuf `json:"codexHome"`
	// Platform family for the running app-server target, for example `"unix"` or `"windows"`.
	PlatformFamily string `json:"platformFamily"`
	// Operating system for the running app-server target, for example `"macos"`, `"linux"`, or `"windows"`.
	PlatformOs string `json:"platformOs"`
	UserAgent  string `json:"userAgent"`
}

// A response to a request that indicates an error occurred.
type JSONRPCError struct {
	Error JSONRPCErrorError `json:"error"`
	Id    RequestId         `json:"id"`
}

type JSONRPCErrorError struct {
	Code    int64           `json:"code"`
	Data    json.RawMessage `json:"data,omitempty"`
	Message string          `json:"message"`
}

// A notification which does not expect a response.
type JSONRPCNotification struct {
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
}

// A request that expects a response.
type JSONRPCRequest struct {
	Id     RequestId       `json:"id"`
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
	// Optional W3C Trace Context for distributed tracing.
	Trace *W3cTraceContext `json:"trace,omitempty"`
}

// A successful (non-error) response to a request.
type JSONRPCResponse struct {
	Id     RequestId       `json:"id"`
	Result json.RawMessage `json:"result"`
}

type RequestId = json.RawMessage

type W3cTraceContext struct {
	Traceparent *string `json:"traceparent,omitempty"`
	Tracestate  *string `json:"tracestate,omitempty"`
}
