import { execFile, execFileSync } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { defineAgent, defineWorkflow } from "@flue/runtime";
import { transcriptEntriesForBackend } from "../lib/transcript-convert.ts";

// Flue HEAD (durable-streams) requires every workflow module to default-export a
// defineWorkflow() definition; a bare `export function run` no longer normalizes.
// This runner is not an LLM agent in the Flue sense (it execFiles a backend CLI),
// so the bound agent is a credential-free stub (model: false, no harness usage).
// The request arrives via env — the task-runner host-bridge sets
// LOOM_TASK_RUN_REQUEST_JSON (driver/task_bridge.go) — which requestPayload()
// already reads, so the inner run() body is unchanged.
export default defineWorkflow({
  agent: defineAgent(() => ({ model: false })),
  run: async () => toJsonResult(await run({ payload: builtinInvokePayload() })),
});

function builtinInvokePayload() {
  const raw = process.env.LOOM_FLUE_INVOKE_PAYLOAD || process.env.LOOM_TASK_RUN_REQUEST_JSON || "{}";
  try {
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

// Flue HEAD validates the workflow return value with a strict JSON check that
// rejects undefined/function/symbol/bigint; round-trip through JSON so optional
// result fields left undefined never throw.
function toJsonResult(value) {
  return value === undefined ? null : JSON.parse(JSON.stringify(value));
}

// scout-task-runner: the scout's workspace-analysis leaf (local-task-runner
// lineage — it execFiles the workspace-default backend CLI directly, it is NOT
// the Flue agent runtime).
//
// Two phases, selected by input.phase:
//
//   "analyze" — enumerate the workspace's attached repo checkouts (direct
//     children of the workspace root that are git checkouts), gather a
//     deterministic context seed (no LLM), then run the backend CLI
//     AGENTICALLY — tools allowed, cwd at the workspace root — so the model can
//     read files itself for deeper grounding (ticket 03: the agentic leaf is
//     the target; the prototype's one-shot is the degraded-mode floor). The
//     model writes its result JSON ({recommendations, skipped, agentsMd}) to a
//     scratch file this runner provides; the parsed + normalized analysis is
//     returned to the scout workflow on runtimeMetadata.scout_analysis. The
//     repos are READ-ONLY by prompt discipline (spec: Trust posture) — this
//     leaf's only writes are its own scratch dir and, in the write phase, the
//     two workspace-root files.
//
//   "write" — apply the workflow-assembled outputs to the workspace root:
//     agents.md (scout-fenced region; first generation auto-applies, human
//     content outside the fences is preserved byte-identical) and history.md
//     (append-only run journal). Writes are atomic tmp+rename, mirroring
//     internal/atomicfile.WriteFile.
//
// Placement guard (spec: File placement and guards): both phases anchor at the
// workspace root and REFUSE to operate when that root resolves to the "."
// fallback or to a git checkout — the scout must never write agents.md /
// history.md inside a repo checkout.

const DEFAULT_BACKEND = "codex";

// SUPPORTED maps each backend to its default binary name, mirroring
// local-task-runner.ts. The binary is overridable via LOOM_<BACKEND>_BIN.
const SUPPORTED = {
  claude: "claude",
  codex: "codex",
  opencode: "opencode",
  gemini: "gemini",
  cursor: "cursor-agent", // the headless agent CLI; `cursor` is the IDE launcher
};

// Hard cap of recommended issues per run (spec: Architecture / The analysis
// leaf). Counts created issues only — skipped duplicates don't count — so the
// leaf emits at most this many candidates and the workflow enforces it again
// before create.
const MAX_RECOMMENDATIONS = 5;

// Fence markers for the scout-owned region of agents.md. Ticket 04 fixed the
// mechanism (scout regenerates only inside its own fences); the spec left the
// spelling to implementation — this is the proposed canonical spelling.
const SCOUT_FENCE_BEGIN = "<!-- scout:begin -->";
const SCOUT_FENCE_END = "<!-- scout:end -->";
const SCOUT_FENCE_NOTE =
  "<!-- Generated by the Loom scout. Content between the scout fences is regenerated by scout runs; edit outside the fences to keep your changes. -->";

const MAX_JOURNAL_CONTEXT_CHARS = 12_000;
const MAX_PRIOR_AGENTS_CONTEXT_CHARS = 8_000;
const MAX_REPO_SEED_CHARS = 9_000;
const MAX_FIELD_CHARS = 16_000;

// Embedded fallback for runs whose role prompt is absent/empty. The catalog's
// prompts/scout.md is the create-only durable seed; this copy keeps already
// queued runs executable if the role record has no prompt.
const DEFAULT_ROLE_PROMPT = `You are the Scout: a proactive analysis agent for a Loom workspace.
Loom is an AI-agent orchestration platform; a workspace groups one or more
repo checkouts that agents work on together.

Workspace root: {{WORKSPACE_ROOT}}
Attached repos ({{REPO_COUNT}}): {{REPO_NAMES}}

--- WORKSPACE CONTEXT (machine-gathered seed; you may verify and dig deeper with your tools) ---
{{WORKSPACE_CONTEXT}}
--- TASK ---
You have file-reading tools: use them to read files under the workspace
root for deeper grounding before you conclude anything. Treat the entire
workspace as READ-ONLY: do not create, modify, or delete any file except
the result file named below; do not run commands with side effects (no
builds, installs, commits, pushes, or network writes).

1. Propose AT MOST {{MAX_RECOMMENDATIONS}} concrete, non-generic work recommendations for
   this workspace — real engineering work a maintainer would plausibly
   accept, grounded in evidence you verified. Prefer fewer, better-grounded
   recommendations over the maximum. Do NOT re-propose work the scout
   journal above already covers (created OR skipped OR closed items stay
   covered); list such candidates under \`skipped\` with a short reason
   instead.
2. Draft the scout-owned content of the workspace-level agents.md.

Rules for each recommendation:
- \`labels\` MUST include "recommended" and "repo:<repo>" for its repo.
- \`priority\` is an integer 0-4 in Loom semantics: 0 = P0 critical, 1 = P1
  high, 2 = P2 normal, 3 = P3 low, 4 = P4 backlog. Most recommendations
  belong at 2-4; reserve 0-1 for genuinely urgent findings.
- \`description\` is the full work description and MUST fold acceptance
  criteria in as a "## Acceptance Criteria" section with verifiable bullets.
- \`rationale\` says why the evidence makes this real, valuable work.
- \`anchors\` are file or directory paths (relative to the repo root) that
  exist and ground the recommendation. Never invent paths.

Rules for the agents.md content:
- Workspace-level facts ONLY — complement, don't duplicate: anything that
  belongs in a single repo's own AGENTS.md is out of bounds.
- Structure: \`## Workspace Overview\`; \`## How the repos relate\`
  (companion-branch ordering, shared contracts, cross-repo test entry
  points); then one section per repo with Build/Test (only commands you
  verified), Architecture Sketch, Conventions, Gotchas.
- Raw markdown, concise, no surrounding code fence, and do NOT include the
  scout fence markers — the runner adds them.

Result delivery: write ONLY a JSON object of the shape
{"recommendations": [{"title", "description", "rationale", "repo",
"labels", "priority", "anchors"}], "skipped": [{"title", "reason"}],
"agentsMd": "..."} to this exact file (create it):
  {{RESULT_PATH}}
Then also print that same JSON object as the final line of your final
message, as a fallback channel. No commentary around it.`;

export async function run(ctx = {}) {
  const request = requestPayload(ctx);
  const taskRunId = stringValue(request.task_run_id || request.taskRunId || process.env.LOOM_TASK_RUN_ID || "scout");
  const input = request.input || {};
  const phase = stringValue(input.phase) || "analyze";
  const logs = [];

  const root = resolveWorkspaceRoot();
  if (!root.ok) {
    return failed("scout_placement_refused", root.reason, { taskRunId, request, phase, logs });
  }
  logs.push("workspace root: " + root.path + " (" + root.source + ")");

  if (phase === "write") {
    return writePhase(root.path, input, taskRunId, request, logs);
  }
  if (phase !== "analyze") {
    return failed("scout_invalid_phase", "unknown scout phase " + JSON.stringify(phase), { taskRunId, request, phase, logs });
  }
  return analyzePhase(root.path, input, taskRunId, request, logs);
}

// resolveWorkspaceRoot anchors both phases at the workspace root — the
// directory cli.GetWorkspaceRuntimeDir() resolves on the Go side. That
// resolver's "." fallback is a real hazard: in single-project mode the
// "workspace runtime dir" IS the repo checkout. Guard (spec: File placement
// and guards):
//   - LOOM_WORKSPACE_RUNTIME_DIR (explicit serve/operator config) wins, but a
//     literal "." — the documented fallback value — is refused.
//   - Otherwise LOOM_WORKTREE_PATH (the executor work dir the task bridge
//     passes for driver-run task runs; scout runs are never worktree-swapped)
//     is used, refusing "", ".", and — belt-and-braces — any directory that is
//     itself a git checkout: that is a repo, not a workspace root.
export function resolveWorkspaceRoot(env = process.env) {
  const runtimeDir = stringValue(env.LOOM_WORKSPACE_RUNTIME_DIR);
  if (runtimeDir) {
    if (runtimeDir === ".") {
      return { ok: false, reason: 'LOOM_WORKSPACE_RUNTIME_DIR resolved to the "." fallback; the scout refuses to write inside a repo checkout' };
    }
    if (!dirExists(runtimeDir)) {
      return { ok: false, reason: "LOOM_WORKSPACE_RUNTIME_DIR " + runtimeDir + " does not exist" };
    }
    return { ok: true, path: path.resolve(runtimeDir), source: "LOOM_WORKSPACE_RUNTIME_DIR" };
  }
  const worktree = stringValue(env.LOOM_WORKTREE_PATH);
  if (!worktree || worktree === ".") {
    return { ok: false, reason: 'no workspace root: LOOM_WORKSPACE_RUNTIME_DIR is unset and LOOM_WORKTREE_PATH is ' + (worktree ? '"."' : "empty") };
  }
  if (!dirExists(worktree)) {
    return { ok: false, reason: "LOOM_WORKTREE_PATH " + worktree + " does not exist" };
  }
  const resolved = path.resolve(worktree);
  if (isGitCheckout(resolved)) {
    return { ok: false, reason: "workspace root fallback " + resolved + " is itself a git checkout; the scout refuses to write inside a repo checkout" };
  }
  return { ok: true, path: resolved, source: "LOOM_WORKTREE_PATH" };
}

// ---------------------------------------------------------------------------
// Phase: analyze
// ---------------------------------------------------------------------------

async function analyzePhase(root, input, taskRunId, request, logs) {
  const repos = await discoverRepos(root);
  logs.push("discovered " + repos.length + " repo checkout(s): " + repos.map((r) => r.name).join(", "));

  // Zero-repo workspaces: no-op the analysis (the run still journals "nothing
  // to analyze" — the workflow drives the write phase either way).
  if (repos.length === 0) {
    return completedAnalysis({
      nothingToAnalyze: true,
      repos: [],
      recommendations: [],
      skipped: [],
      agentsMd: "",
      warnings: ["nothing to analyze: the workspace has no attached repos"],
    }, "none", taskRunId, request, logs);
  }

  const backend = resolveBackend();
  if (!Object.prototype.hasOwnProperty.call(SUPPORTED, backend)) {
    return failed(
      "scout_backend_unsupported",
      `LOOM_TASK_RUNNER_BACKEND=${backend} is not a supported backend (expected one of ${Object.keys(SUPPORTED).join(", ")})`,
      { taskRunId, request, phase: "analyze", logs },
    );
  }
  const binary = resolveBinary(backend);
  if (!binary) {
    return failed(
      "scout_backend_unavailable",
      `${backend} CLI (${SUPPORTED[backend]}) was not found on PATH`,
      { taskRunId, request, phase: "analyze", logs },
    );
  }

  // Dedupe context (slice 1 is LLM-only dedupe, ticket 05): the leaf reads its
  // own journal and instructs the model not to re-propose covered work.
  // TODO(scout, later slice): fleet-db wins on journal loss/conflict — rebuild
  // suppression from open+closed `recommended` issues once a list-issues read
  // path exists for the leaf; there is no such op yet.
  const journal = tailText(readTextSafe(path.join(root, "history.md")), MAX_JOURNAL_CONTEXT_CHARS);
  const priorAgentsMd = capText(scoutFencedContent(readTextSafe(path.join(root, "agents.md"))), MAX_PRIOR_AGENTS_CONTEXT_CHARS);

  // Scratch under the workspace-root .loom dir (protected + never a repo):
  // some backends (opencode) auto-reject writes outside the project directory,
  // so the result file must live under the cwd the agent runs in.
  const scratch = path.join(root, ".loom", "scout", safeName(taskRunId));
  fs.mkdirSync(scratch, { recursive: true });
  const resultPath = path.join(scratch, "result.json");

  const maxRecommendations = clampInt(input.maxRecommendations, 1, MAX_RECOMMENDATIONS, MAX_RECOMMENDATIONS);
  const prompt = analysisPrompt({
    root,
    repos,
    journal,
    priorAgentsMd,
    resultPath,
    maxRecommendations,
    rolePrompt: input.role_prompt,
  });
  logs.push("analysis prompt: " + prompt.length + " chars; backend " + backend);

  let exec;
  try {
    exec = await execBackend(binary, backendArgs(backend, root, prompt), {
      cwd: root,
      input: backendUsesStdinPrompt(backend) ? prompt : undefined,
    });
  } catch (error) {
    return failed("scout_backend_failed", `failed to spawn ${backend} CLI: ${errorMessage(error)}`, { taskRunId, request, phase: "analyze", backend, logs });
  }
  logs.push(`${backend} CLI exit=${exec.code}`);
  if (exec.stdout.trim()) {
    logs.push(textTail(exec.stdout, 100000));
  }
  if (exec.stderr.trim()) {
    logs.push("stderr:\n" + textTail(exec.stderr, 20000));
  }
  const transcriptEntries = transcriptEntriesForBackend(backend, exec.stdout);
  if (exec.code !== 0) {
    removeScratch(scratch, logs);
    return failed("scout_backend_failed", `${backend} CLI exited with code ${exec.code}`, { taskRunId, request, phase: "analyze", backend, logs, transcriptEntries });
  }

  const parsed = parseAnalysisOutput(resultPath, exec.stdout, logs);
  removeScratch(scratch, logs);
  if (!parsed) {
    return failed("scout_no_result", "the analysis run produced no parseable result JSON", { taskRunId, request, phase: "analyze", backend, logs, transcriptEntries });
  }

  const analysis = normalizeAnalysis(parsed, repos, maxRecommendations, root);
  logs.push("analysis: " + analysis.recommendations.length + " recommendation(s), " + analysis.skipped.length + " skipped, " + analysis.warnings.length + " warning(s)");
  return completedAnalysis(analysis, backend, taskRunId, request, logs, transcriptEntries);
}

// discoverRepos enumerates the workspace's attached repo checkouts: direct
// children of the workspace root that are git checkouts (a .git dir or — for
// linked worktrees — a .git file), with HEAD SHA and branch recorded for the
// journal.
async function discoverRepos(root) {
  const repos = [];
  for (const entry of listDirSafe(root)) {
    if (!entry.isDirectory() || entry.name.startsWith(".")) {
      continue;
    }
    const dir = path.join(root, entry.name);
    if (!isGitCheckout(dir)) {
      continue;
    }
    repos.push({
      name: entry.name,
      dir,
      sha: await gitOutput(dir, ["rev-parse", "HEAD"]),
      branch: await gitOutput(dir, ["rev-parse", "--abbrev-ref", "HEAD"]),
    });
  }
  repos.sort((a, b) => a.name.localeCompare(b.name));
  return repos;
}

// analysisPrompt assembles the leaf prompt. Ordering is deliberate for prompt
// cache reuse (spec: Known implementation notes): the shared workspace context
// — intro, per-repo deterministic seed, prior scout agents.md content, the
// journal — comes FIRST and the per-run task text comes LAST.
function analysisPrompt({
  root,
  repos,
  journal,
  priorAgentsMd,
  resultPath,
  maxRecommendations,
  rolePrompt,
}) {
  const context = [];
  for (const repo of repos) {
    context.push(gatherRepoSeed(repo));
  }
  if (priorAgentsMd) {
    context.push(
      "--- CURRENT SCOUT-OWNED agents.md CONTENT (you are regenerating this) ---",
      priorAgentsMd,
      "",
    );
  }
  if (journal) {
    context.push(
      "--- SCOUT JOURNAL (history.md; your memory of previous runs) ---",
      journal,
      "",
    );
  }
  const template = rawString(rolePrompt).trim()
    ? rawString(rolePrompt)
    : DEFAULT_ROLE_PROMPT;
  const values = {
    "{{WORKSPACE_ROOT}}": root,
    "{{REPO_COUNT}}": String(repos.length),
    "{{REPO_NAMES}}": repos.map((repo) => repo.name).join(", "),
    "{{WORKSPACE_CONTEXT}}": context.join("\n"),
    "{{MAX_RECOMMENDATIONS}}": String(maxRecommendations),
    "{{RESULT_PATH}}": resultPath,
  };
  let rendered = template;
  for (const [token, value] of Object.entries(values)) {
    rendered = rendered.split(token).join(value);
  }
  return rendered;
}

// gatherRepoSeed builds the deterministic per-repo context seed (no LLM): the
// agentic leaf largely obsoletes prompt-budget pressure, but the seed keeps the
// model oriented without burning tool calls on discovery.
function gatherRepoSeed(repo) {
  const lines = [];
  lines.push(`## Repo: ${repo.name}`, "");
  lines.push(`HEAD: ${repo.sha || "(unknown)"}${repo.branch ? " (branch " + repo.branch + ")" : ""}`, "");
  const entries = listDirSafe(repo.dir)
    .filter((e) => !e.name.startsWith(".") || e.name === ".github")
    .sort((a, b) => (a.isDirectory() === b.isDirectory() ? a.name.localeCompare(b.name) : a.isDirectory() ? -1 : 1))
    .slice(0, 60)
    .map((e) => e.name + (e.isDirectory() ? "/" : ""));
  lines.push("Top-level entries:", entries.join("  "), "");
  const log = gitLogSafe(repo.dir);
  if (log) {
    lines.push("Recent commits (git log --oneline -15):", log, "");
  }
  return capText(lines.join("\n"), MAX_REPO_SEED_CHARS) + "\n";
}

function gitLogSafe(dir) {
  try {
    return execFileSync("git", ["log", "--oneline", "-15"], { cwd: dir, encoding: "utf8", timeout: 15_000 }).trim();
  } catch {
    return "";
  }
}

async function gitOutput(dir, args) {
  try {
    const result = await execBackend("git", ["-C", dir, ...args], { cwd: dir });
    return result.code === 0 ? result.stdout.trim() : "";
  } catch {
    return "";
  }
}

// parseAnalysisOutput reads the model's result: the scratch result file is the
// primary channel; the backend's stdout (stream-json event text, then a loose
// whole-output parse) is the fallback.
function parseAnalysisOutput(resultPath, stdout, logs) {
  try {
    if (fs.existsSync(resultPath)) {
      return JSON.parse(fs.readFileSync(resultPath, "utf8"));
    }
    logs.push("result file missing: " + resultPath + "; falling back to stdout parse");
  } catch (err) {
    logs.push("result file unparseable (" + errorMessage(err) + "); falling back to stdout parse");
  }
  const lines = String(stdout || "").split("\n");
  for (let i = lines.length - 1; i >= 0; i--) {
    const trimmed = lines[i].trim();
    const start = trimmed.indexOf("{");
    if (start < 0) {
      continue;
    }
    let event;
    try {
      event = JSON.parse(trimmed.slice(start));
    } catch {
      continue;
    }
    for (const candidate of streamEventTexts(event)) {
      if (candidate.includes('"recommendations"')) {
        try {
          return parseLooseJson(candidate);
        } catch {
          // keep scanning
        }
      }
    }
  }
  if (String(stdout || "").includes('"recommendations"')) {
    try {
      return parseLooseJson(stdout);
    } catch {
      return null;
    }
  }
  return null;
}

// streamEventTexts pulls the plausible final-message text fields out of one
// stream-json event, across backends (claude `result`, codex last agent
// message, generic `text`/`message` shapes).
function streamEventTexts(event) {
  const out = [];
  if (!event || typeof event !== "object") {
    return out;
  }
  for (const value of [event.result, event.last_agent_message, event.text, event.message]) {
    if (typeof value === "string" && value.trim()) {
      out.push(value);
    }
  }
  const item = event.item;
  if (item && typeof item === "object" && typeof item.text === "string" && item.text.trim()) {
    out.push(item.text);
  }
  const msg = event.msg;
  if (msg && typeof msg === "object" && typeof msg.message === "string" && msg.message.trim()) {
    out.push(msg.message);
  }
  return out;
}

function parseLooseJson(raw) {
  const text = String(raw || "").trim();
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  return JSON.parse(start >= 0 && end > start ? text.slice(start, end + 1) : text);
}

// normalizeAnalysis validates + repairs the model output deterministically:
// cap the recommendation count (overflow becomes skipped, not created), force
// the quarantine labels, clamp priorities into Loom's 0-4 range, and drop
// anchors that do not exist on disk (recorded as warnings, never fabricated).
function normalizeAnalysis(parsed, repos, maxRecommendations, root) {
  const warnings = [];
  const repoNames = new Set(repos.map((r) => r.name));
  const rawRecs = Array.isArray(parsed && parsed.recommendations) ? parsed.recommendations : [];
  const skipped = [];
  for (const entry of Array.isArray(parsed && parsed.skipped) ? parsed.skipped : []) {
    const title = stringValue(entry && entry.title);
    if (title) {
      skipped.push({ title: capText(title, 500), reason: capText(stringValue(entry.reason) || "already covered", 500) });
    }
  }
  const recommendations = [];
  for (const raw of rawRecs) {
    if (!raw || typeof raw !== "object") {
      continue;
    }
    const title = capText(stringValue(raw.title), 500);
    if (!title) {
      warnings.push("dropped a recommendation with no title");
      continue;
    }
    const repo = stringValue(raw.repo);
    if (!repoNames.has(repo)) {
      warnings.push(`dropped "${title}": unknown repo ${JSON.stringify(repo)}`);
      continue;
    }
    if (recommendations.length >= maxRecommendations) {
      skipped.push({ title, reason: `over the ${maxRecommendations}-per-run cap` });
      continue;
    }
    const labels = [];
    for (const label of Array.isArray(raw.labels) ? raw.labels : []) {
      const value = stringValue(label);
      if (value && !labels.includes(value)) {
        labels.push(value);
      }
    }
    // Quarantine is label-borne: guarantee both labels deterministically
    // rather than trusting prompt adherence ("recommended" is canonical
    // lowercase — fleet-db compares labels case-sensitively).
    if (!labels.includes("recommended")) {
      labels.push("recommended");
    }
    if (!labels.includes("repo:" + repo)) {
      labels.push("repo:" + repo);
    }
    const anchors = [];
    const repoDir = repos.find((r) => r.name === repo).dir;
    for (const anchor of Array.isArray(raw.anchors) ? raw.anchors : []) {
      const rel = stringValue(anchor);
      if (!rel) {
        continue;
      }
      if (fs.existsSync(path.join(repoDir, rel))) {
        anchors.push(rel);
      } else {
        warnings.push(`"${title}": dropped anchor that does not exist on disk: ${rel}`);
      }
    }
    recommendations.push({
      title,
      description: capText(rawString(raw.description), MAX_FIELD_CHARS),
      rationale: capText(rawString(raw.rationale), 4000),
      repo,
      labels,
      priority: clampInt(raw.priority, 0, 4, 2),
      anchors,
    });
  }
  return {
    nothingToAnalyze: false,
    repos: repos.map((r) => ({ name: r.name, sha: r.sha, branch: r.branch })),
    recommendations,
    skipped,
    agentsMd: capText(rawString(parsed && parsed.agentsMd), 64_000),
    warnings,
    root,
  };
}

function completedAnalysis(analysis, backend, taskRunId, request, logs, transcriptEntries) {
  return {
    status: "completed",
    exitCode: 0,
    logs: logs.join("\n") + "\n",
    ...(Array.isArray(transcriptEntries) ? { transcript_entries: transcriptEntries } : {}),
    runtimeMetadata: {
      task_runner: "scout-task-runner",
      runtime_strategy: "scout-analyze-" + backend,
      runner: stringValue(request.runner || "scout-task-runner"),
      phase: "analyze",
      backend,
      scout_analysis: JSON.stringify(analysis),
    },
  };
}

// ---------------------------------------------------------------------------
// Phase: write
// ---------------------------------------------------------------------------

async function writePhase(root, input, taskRunId, request, logs) {
  const agentsMd = rawString(input.agentsMd);
  const entry = input.historyEntry && typeof input.historyEntry === "object" ? input.historyEntry : {};
  let agentsMdMode = "unchanged";
  try {
    if (agentsMd.trim()) {
      agentsMdMode = applyAgentsMd(root, agentsMd);
      logs.push("agents.md: " + agentsMdMode);
    } else {
      logs.push("agents.md: no content to apply");
    }
    const historyMode = appendHistoryEntry(root, entry);
    logs.push("history.md: " + historyMode);
    return {
      status: "completed",
      exitCode: 0,
      logs: logs.join("\n") + "\n",
      runtimeMetadata: {
        task_runner: "scout-task-runner",
        runtime_strategy: "scout-write",
        runner: stringValue(request.runner || "scout-task-runner"),
        phase: "write",
        scout_write: JSON.stringify({
          agentsMdPath: path.join(root, "agents.md"),
          historyPath: path.join(root, "history.md"),
          agentsMdMode,
          historyMode,
        }),
      },
    };
  } catch (err) {
    return failed("scout_write_failed", "writing workspace files failed: " + errorMessage(err), { taskRunId, request, phase: "write", logs });
  }
}

// applyAgentsMd applies the scout-owned content to <root>/agents.md.
// Slice 1 is first-generation auto-apply: no file yet -> create it with the
// scout fences; fences already present -> regenerate ONLY between them (human
// content outside the fences stays byte-identical); a human-owned file with no
// fences -> append the fenced scout block, never rewriting human content.
// TODO(scout, slice 4): weekly re-runs stage agents.md.pending +
// `loom scout diff`/`approve` instead of applying in place.
function applyAgentsMd(root, content) {
  const target = path.join(root, "agents.md");
  const block = SCOUT_FENCE_BEGIN + "\n" + SCOUT_FENCE_NOTE + "\n\n" + content.trim() + "\n" + SCOUT_FENCE_END + "\n";
  const existing = readTextSafe(target);
  if (existing === null) {
    writeFileAtomic(target, block);
    return "created";
  }
  const begin = existing.indexOf(SCOUT_FENCE_BEGIN);
  const end = existing.indexOf(SCOUT_FENCE_END);
  if (begin >= 0 && end > begin) {
    const after = existing.slice(end + SCOUT_FENCE_END.length).replace(/^\n/, "");
    writeFileAtomic(target, existing.slice(0, begin) + block + after);
    return "fences-replaced";
  }
  writeFileAtomic(target, existing.replace(/\n?$/, "\n\n") + block);
  return "fences-appended";
}

// appendHistoryEntry appends one run section to <root>/history.md (creating
// the journal on first run). The journal is append-only pure markdown — the
// next scout run reads it back as dedupe memory (ticket 05).
function appendHistoryEntry(root, entry) {
  const target = path.join(root, "history.md");
  const existing = readTextSafe(target);
  const section = renderHistoryEntry(entry);
  if (existing === null) {
    writeFileAtomic(target, "# Scout journal\n\nAppend-only run log of the Loom scout. The scout reads this file as its dedupe memory; fleet-db `recommended` issues are the durable record.\n\n" + section);
    return "created";
  }
  writeFileAtomic(target, existing.replace(/\n?$/, "\n\n") + section);
  return "appended";
}

// renderHistoryEntry renders one run section. The history.md contract fixes
// the required fields (timestamp, repos + SHAs, issues created, skipped
// candidates, warnings); this markdown shape is the proposed spelling.
function renderHistoryEntry(entry) {
  const lines = [];
  const timestamp = stringValue(entry.timestamp) || new Date().toISOString();
  const runId = stringValue(entry.driverRunId);
  lines.push("## Run " + timestamp + (runId ? " (driver run " + runId + ")" : ""), "");
  if (entry.nothingToAnalyze) {
    lines.push("Nothing to analyze: the workspace has no attached repos.", "");
  }
  lines.push("Repos analyzed:");
  pushList(lines, (Array.isArray(entry.repos) ? entry.repos : []).map((r) => {
    const sha = stringValue(r.sha);
    const branch = stringValue(r.branch);
    return stringValue(r.name) + (sha ? " @ " + sha.slice(0, 12) : "") + (branch && branch !== "HEAD" ? " (branch " + branch + ")" : "");
  }));
  lines.push("", "Issues created:");
  pushList(lines, (Array.isArray(entry.created) ? entry.created : []).map((c) => stringValue(c.id) + " — " + stringValue(c.title)));
  const journaledOnly = Array.isArray(entry.journaledOnly) ? entry.journaledOnly : [];
  if (journaledOnly.length > 0) {
    lines.push("", "Recommendations journaled without issue creation:");
    pushList(lines, journaledOnly.map((r) => stringValue(r.title) + (stringValue(r.repo) ? " (" + stringValue(r.repo) + ")" : "")));
  }
  lines.push("", "Skipped candidates:");
  pushList(lines, (Array.isArray(entry.skipped) ? entry.skipped : []).map((s) => stringValue(s.title) + " — " + stringValue(s.reason)));
  lines.push("", "Warnings:");
  pushList(lines, (Array.isArray(entry.warnings) ? entry.warnings : []).map((w) => stringValue(w)));
  return lines.join("\n") + "\n";
}

function pushList(lines, items) {
  const filtered = items.filter((item) => stringValue(item));
  if (filtered.length === 0) {
    lines.push("- none");
    return;
  }
  for (const item of filtered) {
    lines.push("- " + item);
  }
}

// scoutFencedContent extracts the scout-owned region of an existing agents.md
// (fences excluded) so a re-run can regenerate from what it wrote last time.
export function scoutFencedContent(text) {
  if (text === null) {
    return "";
  }
  const begin = text.indexOf(SCOUT_FENCE_BEGIN);
  const end = text.indexOf(SCOUT_FENCE_END);
  if (begin < 0 || end <= begin) {
    return "";
  }
  return text.slice(begin + SCOUT_FENCE_BEGIN.length, end).trim();
}

// writeFileAtomic mirrors internal/atomicfile.WriteFile: write to a temp file
// in the target's directory, then rename over the target, so readers never see
// a partial file and a failure leaves the original untouched.
function writeFileAtomic(filePath, data) {
  const dir = path.dirname(filePath);
  const tmp = path.join(dir, ".loom-atomic-" + crypto.randomBytes(6).toString("hex"));
  fs.writeFileSync(tmp, data);
  try {
    fs.renameSync(tmp, filePath);
  } catch (err) {
    try {
      fs.unlinkSync(tmp);
    } catch {
      // best-effort cleanup
    }
    throw err;
  }
}

// ---------------------------------------------------------------------------
// Backend invocation (local-task-runner lineage)
// ---------------------------------------------------------------------------

// resolveBackend reads the host-bridge-injected workspace-default backend,
// exactly like local-task-runner (LOOM_TASK_RUNNER_BACKEND, default codex).
export function resolveBackend() {
  return stringValue(process.env.LOOM_TASK_RUNNER_BACKEND).toLowerCase() || DEFAULT_BACKEND;
}

// resolveBinary honors the LOOM_<BACKEND>_BIN override, else searches PATH.
export function resolveBinary(backend, env = process.env) {
  const override = stringValue(env["LOOM_" + backend.toUpperCase() + "_BIN"]);
  if (override) {
    if (override.includes(path.sep) || path.isAbsolute(override)) {
      return isExecutableFile(override) ? override : "";
    }
    const resolved = lookPath(override, env);
    return resolved || (isExecutableFile(override) ? override : "");
  }
  return lookPath(SUPPORTED[backend] || backend, env);
}

function lookPath(name, env) {
  if (name.includes(path.sep) || path.isAbsolute(name)) {
    return isExecutableFile(name) ? name : "";
  }
  const pathValue = stringValue(env.PATH || env.Path || "");
  for (const dir of pathValue.split(path.delimiter).filter(Boolean)) {
    const candidate = path.join(dir, name);
    if (isExecutableFile(candidate)) {
      return candidate;
    }
  }
  return "";
}

// backendArgs mirrors local-task-runner's non-interactive arg builders — the
// AGENTIC invocations with tool use allowed (ticket 03: the scout leaf reads
// files itself; the prototype's tool-less one-shot is the fallback shape, not
// the target). The workspace root is not a git repo, hence codex's
// --skip-git-repo-check.
export function backendArgs(backend, workspaceRoot, prompt) {
  switch (backend) {
    case "codex":
      return ["exec", "--json", "--skip-git-repo-check", "--dangerously-bypass-approvals-and-sandbox", "-"];
    case "claude": {
      const claudeArgs = ["-p", "--verbose", "--output-format", "stream-json", "--dangerously-skip-permissions"];
      const budget = resolveMaxBudgetUSD();
      if (budget) {
        claudeArgs.push("--max-budget-usd", budget);
      }
      const effort = resolveAgentEffort();
      if (effort) {
        claudeArgs.push("--effort", effort);
      }
      claudeArgs.push(prompt);
      return claudeArgs;
    }
    case "gemini":
      return ["--approval-mode=yolo", "-p", prompt, "-o", "stream-json"];
    case "opencode": {
      const opencodeArgs = ["run", "--format", "json", "--dir", workspaceRoot];
      const opencodeModel = stringValue(process.env.LOOM_OPENCODE_MODEL);
      if (opencodeModel) {
        opencodeArgs.push("--model", opencodeModel);
      }
      return opencodeArgs;
    }
    case "cursor":
      return ["-p", "--output-format", "stream-json", "--force", prompt];
    default:
      return [prompt];
  }
}

function backendUsesStdinPrompt(backend) {
  return backend === "opencode" || backend === "codex";
}

// DefaultMaxBudgetUSD / resolveMaxBudgetUSD / resolveAgentEffort mirror
// internal/cli/backends/backend_claude.go via local-task-runner.ts.
const DEFAULT_MAX_BUDGET_USD = 50.0;

function resolveMaxBudgetUSD() {
  const raw = stringValue(process.env.LOOM_MAX_BUDGET_USD);
  if (!raw) {
    return DEFAULT_MAX_BUDGET_USD.toFixed(2);
  }
  const value = Number(raw);
  if (!Number.isFinite(value) || value < 0) {
    return DEFAULT_MAX_BUDGET_USD.toFixed(2);
  }
  if (value === 0) {
    return ""; // explicit opt-out
  }
  return value.toFixed(2);
}

function resolveAgentEffort() {
  return stringValue(process.env.LOOM_AGENT_EFFORT) || stringValue(process.env.LOOM_CLAUDE_EFFORT);
}

async function execBackend(binary, args, options) {
  return await new Promise((resolve, reject) => {
    const child = execFile(
      binary,
      args,
      {
        cwd: options.cwd,
        // IS_SANDBOX=1 mirrors local-task-runner: claude-code refuses
        // --dangerously-skip-permissions under root without it; harmless for
        // the other backends.
        env: { ...(options.env || process.env), IS_SANDBOX: "1" },
        maxBuffer: 64 * 1024 * 1024,
        timeout: numberValue(process.env.LOOM_SCOUT_TASK_TIMEOUT_MS, 30 * 60 * 1000),
      },
      (error, stdout, stderr) => {
        if (error && typeof error.code !== "number" && !error.killed) {
          reject(error);
          return;
        }
        const code = error && typeof error.code === "number" ? error.code : error && error.killed ? 124 : 0;
        resolve({ code, stdout: String(stdout || ""), stderr: String(stderr || "") });
      },
    );
    // Always close stdin: stdin-prompt backends receive the prompt here,
    // positional-prompt backends get an immediate EOF so they never block.
    if (child.stdin) {
      if (options.input !== undefined) {
        child.stdin.end(options.input);
      } else {
        child.stdin.end();
      }
    }
  });
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function requestPayload(ctx) {
  if (ctx && ctx.payload && typeof ctx.payload === "object") {
    return ctx.payload;
  }
  try {
    return JSON.parse(process.env.LOOM_TASK_RUN_REQUEST_JSON || "{}");
  } catch {
    return {};
  }
}

function failed(errorClass, message, { taskRunId, request = {}, phase = "", backend = "", logs = [], transcriptEntries } = {}) {
  const metadata = {
    task_runner: "scout-task-runner",
    runtime_strategy: backend ? "scout-analyze-" + backend : "scout",
    runner: stringValue(request.runner || "scout-task-runner"),
  };
  if (phase) {
    metadata.phase = phase;
  }
  return {
    status: "failed",
    exitCode: 1,
    errorClass,
    errorMessage: message,
    logs: logs.join("\n") + "\n",
    ...(Array.isArray(transcriptEntries) ? { transcript_entries: transcriptEntries } : {}),
    runtimeMetadata: metadata,
  };
}

function removeScratch(scratch, logs) {
  try {
    fs.rmSync(scratch, { recursive: true, force: true });
  } catch (err) {
    logs.push("scratch cleanup warning: " + errorMessage(err));
  }
}

function listDirSafe(dir) {
  try {
    return fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return [];
  }
}

function dirExists(filePath) {
  try {
    return fs.statSync(filePath).isDirectory();
  } catch {
    return false;
  }
}

// isGitCheckout treats both a .git directory (normal clone) and a .git file
// (linked worktree) as a checkout.
function isGitCheckout(dir) {
  return fs.existsSync(path.join(dir, ".git"));
}

function isExecutableFile(filePath) {
  try {
    const stat = fs.statSync(filePath);
    if (!stat.isFile()) {
      return false;
    }
    fs.accessSync(filePath, fs.constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

// readTextSafe returns the file's text, or null when it does not exist /
// cannot be read (the two are equivalent for the scout's purposes).
function readTextSafe(filePath) {
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch {
    return null;
  }
}

function tailText(text, maxChars) {
  if (text === null) {
    return "";
  }
  return text.length > maxChars ? "… [journal head truncated]\n" + text.slice(text.length - maxChars) : text;
}

function capText(text, maxChars) {
  const s = String(text || "");
  return s.length > maxChars ? s.slice(0, maxChars) + "\n… [truncated]" : s;
}

function textTail(text, maxChars) {
  const s = String(text || "");
  return s.length > maxChars ? "…" + s.slice(s.length - maxChars) : s;
}

function safeName(value) {
  return stringValue(value).replace(/[^A-Za-z0-9_.-]/g, "_") || "scout";
}

function clampInt(value, min, max, fallback) {
  const n = Number(value);
  if (!Number.isInteger(n)) {
    return fallback;
  }
  return Math.min(max, Math.max(min, n));
}

function stringValue(value) {
  return value === undefined || value === null ? "" : String(value).trim();
}

function rawString(value) {
  return value === undefined || value === null ? "" : String(value);
}

function numberValue(value, fallback) {
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function errorMessage(err) {
  return err && err.message ? err.message : String(err);
}
