package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const miniSpec = `openapi: 3.1.0
info:
  title: Test API
  description: Test description.
  version: 9.9.9
servers:
  - url: http://localhost:8080
    description: Local
tags:
  - name: health
    description: Health checks
  - name: issues
    description: Issue CRUD
security:
  - BearerAuth: []
paths:
  /health:
    get:
      operationId: getHealth
      tags: [health]
      summary: Liveness probe
      security: []
      responses:
        "200":
          description: OK
  /api/workspaces/{ws}/issues/{id}:
    parameters:
      - $ref: "#/components/parameters/WorkspaceId"
    patch:
      operationId: updateIssue
      tags: [issues]
      summary: Update an issue
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title]
              properties:
                title:
                  type: string
                notes:
                  type: [string, "null"]
      responses:
        "500":
          description: Boom
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Issue"
  /api/ghost:
    get:
      operationId: ghost
      tags: [issues]
      summary: Not registered anywhere
      responses:
        "200":
          description: OK
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  parameters:
    WorkspaceId:
      name: ws
      in: path
      required: true
      description: Workspace identifier
      schema:
        type: string
  schemas:
    Issue:
      type: object
      description: An issue.
      required: [id]
      properties:
        id:
          type: string
        state:
          type: string
          enum: [open, closed]
`

const miniRoutes = `package fake

import "net/http"

func register(mux *http.ServeMux) {
	mux.HandleFunc("GET /health", nil)
	mux.HandleFunc("PATCH /api/workspaces/{ws}/issues/{issueId}", nil)
	mux.HandleFunc("POST /api/undocumented", nil)
	mux.Handle("/api/proxy/", nil)
	notARoute("GET /api/decoy", nil)
}

func notARoute(string, http.Handler) {}
`

// writeFixture lays out a spec, partials, and a fake route package in a temp
// dir and returns the paths run() needs.
func writeFixture(t *testing.T) (specPath, preamble, appendix, routesDir, root string) {
	t.Helper()
	root = t.TempDir()
	specPath = filepath.Join(root, "openapi.yaml")
	preamble = filepath.Join(root, "preamble.md")
	appendix = filepath.Join(root, "appendix.md")
	routesDir = filepath.Join(root, "webui")

	mustWrite(t, specPath, miniSpec)
	mustWrite(t, preamble, "## Handwritten Preamble\n\nKeep me.\n")
	mustWrite(t, appendix, "## Handwritten Appendix\n\nKeep me too.\n")
	if err := os.MkdirAll(routesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	mustWrite(t, filepath.Join(routesDir, "routes.go"), miniRoutes)
	mustWrite(t, filepath.Join(routesDir, "routes_test.go"), "package fake\n")
	return specPath, preamble, appendix, routesDir, root
}

func mustWrite(t *testing.T, path, body string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
}

func generate(t *testing.T) string {
	t.Helper()
	spec, pre, app, routes, root := writeFixture(t)
	out, err := run(spec, pre, app, routes, root, "gen-api-docs")
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	return out
}

func TestGeneratedDocumentStructure(t *testing.T) {
	out := generate(t)

	wants := []string{
		"<!-- Code generated by scripts/openapi-to-md. DO NOT EDIT. -->",
		"Run `make gen-api-docs`",
		"# Test API",
		"## Handwritten Preamble",
		"## Handwritten Appendix",
		"#### `GET /health`",
		"- **Auth:** **None** (public route)",
		"#### `PATCH /api/workspaces/{ws}/issues/{id}`",
		"- **Auth:** `BearerAuth` (document default)",
		"### Schema: Issue",
		"`state` | `string` enum: `open`, `closed`",
		"[Issue](#schema-issue)",
	}
	for _, want := range wants {
		if !strings.Contains(out, want) {
			t.Errorf("output is missing %q", want)
		}
	}
}

func TestPathLevelParameterIsInherited(t *testing.T) {
	out := generate(t)
	// The `ws` parameter is declared on the path item and only resolvable
	// through components.parameters; both must survive into the operation.
	if !strings.Contains(out, "| `ws` | path | yes | `string` | Workspace identifier |") {
		t.Error("path-level $ref parameter was not resolved into the operation table")
	}
	if !strings.Contains(out, "| `id` | path | yes | `string` | — |") {
		t.Error("operation-level parameter missing")
	}
}

func TestNullableTypeAndRequiredFlagsRender(t *testing.T) {
	out := generate(t)
	if !strings.Contains(out, "| `notes` | `string`, nullable | no | — |") {
		t.Error("3.1 nullable type list did not render")
	}
	if !strings.Contains(out, "| `title` | `string` | yes | — |") {
		t.Error("required request body field did not render")
	}
}

func TestResponsesSortNumerically(t *testing.T) {
	out := generate(t)
	got200 := strings.Index(out, "| `200` | Updated |")
	got500 := strings.Index(out, "| `500` | Boom |")
	if got200 < 0 || got500 < 0 {
		t.Fatalf("responses missing: 200=%d 500=%d", got200, got500)
	}
	if got200 > got500 {
		t.Error("responses are not sorted numerically (500 rendered before 200)")
	}
}

func TestCoverageAppendixClassifiesDrift(t *testing.T) {
	out := generate(t)

	// Registered but absent from the spec.
	if !strings.Contains(out, "| POST | `/api/undocumented` |") {
		t.Error("undocumented route not reported")
	}
	// Declared in the spec but registered nowhere.
	if !strings.Contains(out, "| GET | `/api/ghost` | `ghost` |") {
		t.Error("phantom spec path not reported")
	}
	// Placeholder names differ ({id} vs {issueId}) but the route matches.
	if strings.Contains(out, "| PATCH | `/api/workspaces/{ws}/issues/{issueId}` |") {
		t.Error("route matched only by placeholder name was reported as drift")
	}
	// Test files and non-registration calls must not be scanned.
	if strings.Contains(out, "/api/decoy") {
		t.Error("a non-registration call was treated as a route")
	}
}

func TestScanRoutesSeparatesMountsFromRoutes(t *testing.T) {
	_, _, _, routesDir, root := writeFixture(t)
	routes, mounts, err := scanRoutes(routesDir, root)
	if err != nil {
		t.Fatalf("scanRoutes: %v", err)
	}
	if len(routes) != 3 {
		t.Fatalf("routes = %d, want 3: %#v", len(routes), routes)
	}
	if len(mounts) != 1 || mounts[0].Path != "/api/proxy/" {
		t.Fatalf("mounts = %#v", mounts)
	}
	// Sorted by path, then canonical method order.
	if routes[0].Path != "/api/undocumented" || routes[len(routes)-1].Path != "/health" {
		t.Errorf("routes not sorted: %#v", routes)
	}
	if routes[0].File != "webui/routes.go" || routes[0].Line == 0 {
		t.Errorf("route provenance wrong: %#v", routes[0])
	}
}

func TestOpaqueMountCoversSpecPathButEnumeratedMountDoesNot(t *testing.T) {
	routes := []Route{{Method: "GET", Path: "/api/workspaces/{ws}/issues"}}
	mounts := []Route{
		{Path: "/api/proxy/", File: "f.go", Line: 1},
		{Path: "/api/workspaces/{ws}/", File: "f.go", Line: 2},
	}
	ops := []SpecOperation{
		{Method: "GET", Path: "/api/proxy/thing", Op: &Operation{}},
		{Method: "GET", Path: "/api/workspaces/{ws}/gone", Op: &Operation{}},
	}
	d := compareRoutes(ops, routes, mounts)

	if len(d.MountedPaths) != 1 || d.MountedPaths[0].Path != "/api/proxy/thing" {
		t.Errorf("MountedPaths = %#v", d.MountedPaths)
	}
	// /api/workspaces/{ws}/ has enumerable children, so it must not be treated
	// as a wildcard that hides a removed endpoint.
	if len(d.PhantomPaths) != 1 || d.PhantomPaths[0].Path != "/api/workspaces/{ws}/gone" {
		t.Errorf("PhantomPaths = %#v", d.PhantomPaths)
	}
	if len(d.UndocumentedRoutes) != 1 {
		t.Errorf("UndocumentedRoutes = %#v", d.UndocumentedRoutes)
	}
}

func TestOutputIsDeterministic(t *testing.T) {
	spec, pre, app, routes, root := writeFixture(t)
	first, err := run(spec, pre, app, routes, root, "gen-api-docs")
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 5; i++ {
		next, err := run(spec, pre, app, routes, root, "gen-api-docs")
		if err != nil {
			t.Fatal(err)
		}
		if next != first {
			t.Fatalf("run %d differed from run 0", i+1)
		}
	}
}

func TestMissingPartialIsAnError(t *testing.T) {
	spec, _, app, routes, root := writeFixture(t)
	if _, err := run(spec, filepath.Join(root, "nope.md"), app, routes, root, "t"); err == nil {
		t.Fatal("expected an error when the preamble is missing")
	}
}

func TestMarkdownCellEscaping(t *testing.T) {
	if got := mdCell("a | b\nc"); got != "a \\| b c" {
		t.Errorf("mdCell = %q", got)
	}
	if got := mdCell("   "); got != "—" {
		t.Errorf("mdCell blank = %q", got)
	}
}

func TestNormalizePathErasesPlaceholderNames(t *testing.T) {
	if normalizePath("/a/{id}/b/{name}") != normalizePath("/a/{issueId}/b/{agent}") {
		t.Error("placeholder names leaked into the comparison key")
	}
	if normalizePath("/a/{id}") == normalizePath("/a/{id}/b") {
		t.Error("distinct paths collapsed")
	}
}
