package main

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// renderer accumulates the generated markdown document.
type renderer struct {
	spec  *Spec
	buf   strings.Builder
	drift Drift
	// genTarget is the make target quoted in the do-not-edit banner.
	genTarget string
}

func (r *renderer) line(format string, args ...any) {
	if len(args) == 0 {
		r.buf.WriteString(format)
	} else {
		fmt.Fprintf(&r.buf, format, args...)
	}
	r.buf.WriteByte('\n')
}

func (r *renderer) blank() { r.buf.WriteByte('\n') }

// raw appends checked-in prose verbatim, normalizing trailing whitespace so the
// output is byte-stable regardless of how the partial file ends.
func (r *renderer) raw(s string) {
	s = strings.TrimRight(s, "\n")
	if s == "" {
		return
	}
	r.buf.WriteString(s)
	r.buf.WriteString("\n\n")
}

// render produces the whole document.
func (r *renderer) render(preamble, appendix string) string {
	r.renderBanner()
	r.raw(preamble)
	r.renderServers()
	r.renderSecuritySchemes()
	r.renderIndex()
	r.renderEndpoints()
	r.renderSchemas()
	r.raw(appendix)
	r.renderCoverage()
	return strings.TrimRight(r.buf.String(), "\n") + "\n"
}

func (r *renderer) renderBanner() {
	r.line("<!-- Code generated by scripts/openapi-to-md. DO NOT EDIT. -->")
	r.line("<!-- Endpoint reference is generated from api/openapi.yaml. -->")
	r.line("<!-- Hand-written prose lives in docs/api.preamble.md and docs/api.appendix.md. -->")
	r.line("<!-- Regenerate with: make %s -->", r.genTarget)
	r.blank()
	r.line("# %s", r.spec.Info.Title)
	r.blank()
	r.line("**Generated file — do not edit by hand. Run `make %s`.**", r.genTarget)
	r.blank()
	r.line("The endpoint reference below is generated from `api/openapi.yaml`, which is")
	r.line("staleness-gated against the committed Go types by `make check-go-api-staleness`.")
	r.line("Prose sections come from `docs/api.preamble.md` and `docs/api.appendix.md`;")
	r.line("edit those files, not this one.")
	r.blank()
	if d := strings.TrimSpace(r.spec.Info.Description); d != "" {
		r.line("Spec version: `%s`.", r.spec.Info.Version)
		r.blank()
		r.raw(d)
	}
}

func (r *renderer) renderServers() {
	if len(r.spec.Servers) == 0 {
		return
	}
	r.line("## Servers")
	r.blank()
	for _, s := range r.spec.Servers {
		if s.Description != "" {
			r.line("- `%s` — %s", s.URL, oneLine(s.Description))
		} else {
			r.line("- `%s`", s.URL)
		}
	}
	r.blank()
}

func (r *renderer) renderSecuritySchemes() {
	if r.spec.Components.SecuritySchemes.Len() == 0 {
		return
	}
	r.line("## Security Schemes")
	r.blank()
	r.line("The document-level default is %s.", r.securityLabel(&r.spec.Security))
	r.line("An operation that declares `security: []` overrides that and is public.")
	r.blank()
	for _, name := range r.spec.Components.SecuritySchemes.Keys() {
		s, _ := r.spec.Components.SecuritySchemes.Get(name)
		r.line("### `%s`", name)
		r.blank()
		kind := s.Type
		switch {
		case s.Scheme != "" && s.BearerFormat != "":
			kind = fmt.Sprintf("%s, scheme `%s`, format `%s`", s.Type, s.Scheme, s.BearerFormat)
		case s.Scheme != "":
			kind = fmt.Sprintf("%s, scheme `%s`", s.Type, s.Scheme)
		case s.In != "" && s.Name != "":
			kind = fmt.Sprintf("%s in `%s`, name `%s`", s.Type, s.In, s.Name)
		}
		r.line("- **Kind:** %s", kind)
		r.blank()
		if d := strings.TrimSpace(s.Description); d != "" {
			r.raw(d)
		}
	}
}

// tagGroup is a set of operations sharing a primary tag.
type tagGroup struct {
	Name        string
	Description string
	Ops         []SpecOperation
}

// groupByTag buckets operations by their first tag, ordered by the spec's
// declared tag list. Operations whose tag is undeclared (or that carry no tag)
// land in trailing groups sorted by name so the output stays deterministic.
func (r *renderer) groupByTag() []tagGroup {
	declared := make(map[string]int, len(r.spec.Tags))
	groups := make([]tagGroup, 0, len(r.spec.Tags))
	for i, t := range r.spec.Tags {
		declared[t.Name] = i
		groups = append(groups, tagGroup{Name: t.Name, Description: t.Description})
	}
	extra := map[string]*tagGroup{}
	for _, op := range r.spec.operations() {
		name := "untagged"
		if len(op.Op.Tags) > 0 {
			name = op.Op.Tags[0]
		}
		if idx, ok := declared[name]; ok {
			groups[idx].Ops = append(groups[idx].Ops, op)
			continue
		}
		g, ok := extra[name]
		if !ok {
			g = &tagGroup{Name: name}
			extra[name] = g
		}
		g.Ops = append(g.Ops, op)
	}
	extraNames := make([]string, 0, len(extra))
	for name := range extra {
		extraNames = append(extraNames, name)
	}
	sort.Strings(extraNames)
	for _, name := range extraNames {
		groups = append(groups, *extra[name])
	}
	out := groups[:0]
	for _, g := range groups {
		if len(g.Ops) > 0 {
			out = append(out, g)
		}
	}
	return out
}

func (r *renderer) renderIndex() {
	ops := r.spec.operations()
	r.line("## Endpoint Index")
	r.blank()
	r.line("%d operations across %d paths.", len(ops), r.spec.Paths.Len())
	r.blank()
	r.line("| Method | Path | Tag | Summary |")
	r.line("|--------|------|-----|---------|")
	for _, g := range r.groupByTag() {
		for _, op := range g.Ops {
			r.line("| %s | `%s` | %s | %s |",
				op.Method, op.Path, g.Name, mdCell(op.Op.Summary))
		}
	}
	r.blank()
}

func (r *renderer) renderEndpoints() {
	r.line("## Endpoints")
	r.blank()
	for _, g := range r.groupByTag() {
		r.line("### Tag: %s", g.Name)
		r.blank()
		if g.Description != "" {
			r.line("%s", oneLine(g.Description))
			r.blank()
		}
		for _, op := range g.Ops {
			r.renderOperation(op)
		}
	}
}

func (r *renderer) renderOperation(so SpecOperation) {
	op := so.Op
	r.line("#### `%s %s`", so.Method, so.Path)
	r.blank()
	if op.Deprecated {
		r.line("**Deprecated.**")
		r.blank()
	}
	if op.Summary != "" {
		r.line("%s", oneLine(op.Summary))
		r.blank()
	}
	if d := strings.TrimSpace(op.Description); d != "" {
		r.raw(d)
	}
	if op.OperationID != "" {
		r.line("- **Operation ID:** `%s`", op.OperationID)
	}
	r.line("- **Auth:** %s", r.securityLabel(op.Security))
	r.blank()

	params := append(append([]Parameter{}, so.PathParams...), op.Parameters...)
	r.renderParams(params)
	r.renderRequestBody(op.RequestBody)
	r.renderResponses(op.Responses)
}

func (r *renderer) renderParams(params []Parameter) {
	if len(params) == 0 {
		return
	}
	r.line("**Parameters**")
	r.blank()
	r.line("| Name | In | Required | Type | Description |")
	r.line("|------|----|----------|------|-------------|")
	for _, p := range params {
		p = r.spec.resolveParam(p)
		if p.Name == "" && p.Ref != "" {
			r.line("| _unresolved_ | | | | `%s` |", mdCell(p.Ref))
			continue
		}
		r.line("| `%s` | %s | %s | %s | %s |",
			p.Name, p.In, yesNo(p.Required), r.schemaSummary(p.Schema), mdCell(p.Description))
	}
	r.blank()
}

func (r *renderer) renderRequestBody(rb *RequestBody) {
	if rb == nil {
		return
	}
	r.line("**Request body** (%s)", requiredWord(rb.Required))
	r.blank()
	if d := strings.TrimSpace(rb.Description); d != "" {
		r.raw(d)
	}
	r.line("| Content-Type | Schema |")
	r.line("|--------------|--------|")
	for _, ct := range rb.Content.Keys() {
		mt, _ := rb.Content.Get(ct)
		r.line("| `%s` | %s |", ct, r.schemaSummary(mt.Schema))
	}
	r.blank()
	for _, ct := range rb.Content.Keys() {
		mt, _ := rb.Content.Get(ct)
		r.renderInlineObject(mt.Schema)
	}
}

func (r *renderer) renderResponses(resp orderedMap[Response]) {
	if resp.Len() == 0 {
		return
	}
	r.line("**Responses**")
	r.blank()
	r.line("| Status | Description | Schema |")
	r.line("|--------|-------------|--------|")
	for _, status := range sortStatuses(resp.Keys()) {
		res, _ := resp.Get(status)
		schema := "—"
		if res.Content.Len() > 0 {
			parts := make([]string, 0, res.Content.Len())
			for _, ct := range res.Content.Keys() {
				mt, _ := res.Content.Get(ct)
				parts = append(parts, fmt.Sprintf("`%s`: %s", ct, r.schemaSummary(mt.Schema)))
			}
			schema = strings.Join(parts, "<br>")
		}
		r.line("| `%s` | %s | %s |", status, mdCell(res.Description), schema)
	}
	r.blank()
	for _, status := range sortStatuses(resp.Keys()) {
		res, _ := resp.Get(status)
		if res.Headers.Len() > 0 {
			r.line("Response headers (`%s`):", status)
			r.blank()
			for _, h := range res.Headers.Keys() {
				hdr, _ := res.Headers.Get(h)
				r.line("- `%s` — %s%s", h, r.schemaSummary(hdr.Schema), suffixDesc(hdr.Description))
			}
			r.blank()
		}
	}
}

// renderInlineObject expands an anonymous object schema into a property table.
// Named schemas are linked instead, and documented once under "Schemas".
func (r *renderer) renderInlineObject(s *Schema) {
	if s == nil || s.Ref != "" || s.Properties.Len() == 0 {
		return
	}
	r.line("Body fields:")
	r.blank()
	r.renderPropertyTable(s)
}

func (r *renderer) renderPropertyTable(s *Schema) {
	required := make(map[string]bool, len(s.Required))
	for _, name := range s.Required {
		required[name] = true
	}
	r.line("| Field | Type | Required | Description |")
	r.line("|-------|------|----------|-------------|")
	for _, name := range s.Properties.Keys() {
		p, _ := s.Properties.Get(name)
		r.line("| `%s` | %s | %s | %s |",
			name, r.schemaSummary(&p), yesNo(required[name]), mdCell(p.Description))
	}
	r.blank()
}

func (r *renderer) renderSchemas() {
	schemas := r.spec.Components.Schemas
	if schemas.Len() == 0 {
		return
	}
	names := append([]string{}, schemas.Keys()...)
	sort.Strings(names)

	r.line("## Schemas")
	r.blank()
	r.line("Reusable schemas from `api/openapi.yaml` (`components.schemas`), sorted by name.")
	r.blank()
	for _, name := range names {
		s, _ := schemas.Get(name)
		r.line("### Schema: %s", name)
		r.blank()
		if d := strings.TrimSpace(s.Description); d != "" {
			r.raw(d)
		}
		r.line("- **Type:** %s", r.schemaSummary(&s))
		r.blank()
		switch {
		case s.Properties.Len() > 0:
			r.renderPropertyTable(&s)
		case len(s.AllOf) > 0:
			for i := range s.AllOf {
				if s.AllOf[i].Properties.Len() > 0 {
					r.renderPropertyTable(&s.AllOf[i])
				}
			}
		}
	}
}

func (r *renderer) renderCoverage() {
	r.line("## Appendix: Spec Coverage vs Registered Routes")
	r.blank()
	r.line("Generated by comparing `api/openapi.yaml` against the `net/http` route")
	r.line("patterns registered under `internal/webui/`. See `scripts/openapi-to-md/routes.go`")
	r.line("for the detection rule and its limits — it is a syntactic scan, so a route")
	r.line("built from a non-literal pattern would not appear here, and conditionally")
	r.line("registered routes are listed even when their dependency is nil at runtime.")
	r.blank()
	r.line("Provenance is file-level on purpose. This document is staleness-gated, and")
	r.line("citing `file:line` would make every unrelated edit above a registration")
	r.line("(a new import, a doc comment) fail the gate without any API change.")
	r.blank()
	r.renderCoverageStats()
	r.renderUndocumentedRoutes()
	r.renderMountedPaths()
	r.renderPhantomPaths()
}

func (r *renderer) renderCoverageStats() {
	r.line("| Metric | Count |")
	r.line("|--------|-------|")
	r.line("| Spec operations | %d |", len(r.spec.operations()))
	r.line("| Registered routes found in Go | %d |", r.drift.RouteCount)
	r.line("| Matched | %d |", r.drift.Matched)
	r.line("| Registered but undocumented | %d |", len(r.drift.UndocumentedRoutes))
	r.line("| Documented, served by a subtree mount | %d |", len(r.drift.MountedPaths))
	r.line("| Documented but not registered | %d |", len(r.drift.PhantomPaths))
	r.blank()
}

func (r *renderer) renderUndocumentedRoutes() {
	r.line("### Registered but missing from `api/openapi.yaml`")
	r.blank()
	if len(r.drift.UndocumentedRoutes) == 0 {
		r.line("None.")
		r.blank()
		return
	}
	r.line("These routes serve traffic but have no spec entry, so they are absent from")
	r.line("the endpoint reference above and from the generated Go and TypeScript types.")
	r.blank()
	r.line("| Method | Path | Registered in |")
	r.line("|--------|------|---------------|")
	for _, rt := range r.drift.UndocumentedRoutes {
		r.line("| %s | `%s` | `%s` |", rt.Method, rt.Path, rt.File)
	}
	r.blank()
}

func (r *renderer) renderMountedPaths() {
	if len(r.drift.MountedPaths) == 0 {
		return
	}
	r.line("### Documented, served by a subtree mount")
	r.blank()
	r.line("No route of their own, but an opaque `mux.Handle` subtree forwards every")
	r.line("path beneath it — so these are served, not missing.")
	r.blank()
	r.line("| Method | Path | Mount |")
	r.line("|--------|------|-------|")
	for _, m := range r.drift.MountedPaths {
		r.line("| %s | `%s` | `%s` in `%s` |",
			m.Method, m.Path, m.Mount.Path, m.Mount.File)
	}
	r.blank()
}

func (r *renderer) renderPhantomPaths() {
	r.line("### Documented but not registered")
	r.blank()
	if len(r.drift.PhantomPaths) == 0 {
		r.line("None.")
		r.blank()
		return
	}
	r.line("These operations appear in the spec (and therefore in the endpoint reference")
	r.line("above and in the generated types) but no matching route registration was")
	r.line("found. Treat them as unavailable until the spec is corrected.")
	r.blank()
	r.line("| Method | Path | Operation ID |")
	r.line("|--------|------|--------------|")
	for _, op := range r.drift.PhantomPaths {
		r.line("| %s | `%s` | `%s` |", op.Method, op.Path, op.Op.OperationID)
	}
	r.blank()
}

// securityLabel renders an operation's effective auth requirement.
func (r *renderer) securityLabel(sec *[]map[string][]string) string {
	if sec == nil {
		if len(r.spec.Security) == 0 {
			return "none declared"
		}
		return schemeNames(r.spec.Security) + " (document default)"
	}
	if len(*sec) == 0 {
		return "**None** (public route)"
	}
	return schemeNames(*sec)
}

// schemeNames formats a security requirement list as backticked scheme names.
func schemeNames(reqs []map[string][]string) string {
	var names []string
	for _, req := range reqs {
		keys := make([]string, 0, len(req))
		for k := range req {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			names = append(names, "`"+k+"`")
		}
	}
	if len(names) == 0 {
		return "none declared"
	}
	return strings.Join(names, " or ")
}

// schemaSummary renders a one-cell description of a schema.
func (r *renderer) schemaSummary(s *Schema) string {
	if s.isEmpty() {
		return "—"
	}
	if s.Ref != "" {
		return r.refSummary(s.Ref)
	}
	if len(s.AllOf) > 0 {
		parts := make([]string, 0, len(s.AllOf))
		for i := range s.AllOf {
			parts = append(parts, r.schemaSummary(&s.AllOf[i]))
		}
		return "allOf(" + strings.Join(parts, " + ") + ")"
	}

	types, nullable := splitNull(s.Type)
	base := r.baseTypeSummary(s, types)
	if len(s.Enum) > 0 {
		base += " enum: " + enumValues(s.Enum)
	}
	if s.Const != nil {
		base += fmt.Sprintf(" const `%v`", s.Const)
	}
	if s.Type != nil && s.AdditionalProperties.Schema != nil && s.AdditionalProperties.Schema.Ref != "" {
		base += " of " + r.schemaSummary(s.AdditionalProperties.Schema)
	}
	if nullable || s.Nullable {
		base += ", nullable"
	}
	return base
}

// refSummary renders a `$ref` as a link into the Schemas section when the
// target is a known component, and as inline code otherwise.
func (r *renderer) refSummary(ref string) string {
	name := refName(ref)
	if name == "" {
		return "`" + ref + "`"
	}
	if _, ok := r.spec.Components.Schemas.Get(name); ok {
		return fmt.Sprintf("[%s](#schema-%s)", name, anchor(name))
	}
	return "`" + name + "`"
}

// baseTypeSummary renders the type portion of a schema summary, before enum,
// const, additionalProperties, and nullability suffixes are appended.
func (r *renderer) baseTypeSummary(s *Schema, types []string) string {
	switch {
	case len(types) == 0 && s.Properties.Len() > 0:
		return "`object`"
	case len(types) == 0 && len(s.Enum) > 0:
		return "enum"
	case len(types) == 0:
		return "—"
	case types[0] == "array":
		return "array of " + r.schemaSummary(s.Items)
	}
	base := "`" + strings.Join(types, "\\|") + "`"
	if s.Format != "" {
		base += " (`" + s.Format + "`)"
	}
	return base
}

// splitNull separates the JSON Schema "null" member from a 3.1 type list.
func splitNull(types stringList) ([]string, bool) {
	var kept []string
	var nullable bool
	for _, t := range types {
		if t == "null" {
			nullable = true
			continue
		}
		kept = append(kept, t)
	}
	return kept, nullable
}

// enumValues formats enum members deterministically.
func enumValues(vals []any) string {
	parts := make([]string, 0, len(vals))
	for _, v := range vals {
		parts = append(parts, fmt.Sprintf("`%v`", v))
	}
	return strings.Join(parts, ", ")
}

// sortStatuses orders response keys: numeric ascending, then the rest
// alphabetically (which puts `default` last).
func sortStatuses(keys []string) []string {
	out := append([]string{}, keys...)
	sort.SliceStable(out, func(i, j int) bool {
		ni, erri := strconv.Atoi(out[i])
		nj, errj := strconv.Atoi(out[j])
		switch {
		case erri == nil && errj == nil:
			return ni < nj
		case erri == nil:
			return true
		case errj == nil:
			return false
		default:
			return out[i] < out[j]
		}
	})
	return out
}

// anchor converts a schema name into the heading slug GitHub would generate for
// "### Schema: <name>".
func anchor(name string) string {
	var b strings.Builder
	for _, ch := range strings.ToLower(name) {
		switch {
		case ch >= 'a' && ch <= 'z', ch >= '0' && ch <= '9', ch == '-', ch == '_':
			b.WriteRune(ch)
		case ch == ' ':
			b.WriteByte('-')
		}
	}
	return b.String()
}

// oneLine collapses a multi-line string into a single line.
func oneLine(s string) string {
	return strings.Join(strings.Fields(strings.TrimSpace(s)), " ")
}

// mdCell makes a string safe to place inside a markdown table cell.
func mdCell(s string) string {
	s = oneLine(s)
	if s == "" {
		return "—"
	}
	return strings.ReplaceAll(s, "|", "\\|")
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func requiredWord(b bool) string {
	if b {
		return "required"
	}
	return "optional"
}

func suffixDesc(s string) string {
	if s = oneLine(s); s == "" {
		return ""
	}
	return " — " + s
}
