package main

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"

	"golang.org/x/tools/go/packages"
)

// refDir is the checked-in output directory for every generated reference doc
// and its optional hand-written preamble. Repo-relative; joined onto RepoRoot.
const refDir = "docs/reference"

// defaultMakeTarget is the make target named in each generated file's banner.
// The staleness gate (added in a later phase) will diff a fresh regen against
// the committed file, so the banner tells a human exactly how to refresh it.
const defaultMakeTarget = "docs-gen"

// genBanner is the machine-recognizable "do not edit" marker. It matches the
// Go toolchain's generated-file convention (`Code generated ... DO NOT EDIT.`)
// so editors and tooling treat the output as generated, exactly like the
// sibling scripts/openapi-to-md generator.
const genBanner = "Code generated by scripts/loomdoc. DO NOT EDIT."

// loadMode is the go/packages configuration every generator loads against. It
// deliberately requests full type information: the env-vars generator resolves
// os.Getenv/os.LookupEnv/os.Setenv arguments that are named constants (e.g.
// os.Getenv(EnvFleetDBBin) at internal/bootstrap/embedded.go), which is only
// possible with NeedTypes|NeedTypesInfo|NeedDeps. The layers generator reads
// the import graph, which needs NeedImports|NeedDeps.
const loadMode = packages.NeedName | packages.NeedFiles | packages.NeedSyntax |
	packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports |
	packages.NeedDeps | packages.NeedModule

// genConfig is the shared context handed to every generator. Construct one per
// process with newGenConfig, then pass it to each generateXxx function. The
// loaded package graph is memoized so a "generate all" run pays the (expensive)
// go/packages load exactly once and every generator reuses it.
//
// genConfig is the Phase 2 contract: generators read RepoRoot, MakeTarget, the
// Tracked predicate, and Packages(); they must not load packages themselves.
type genConfig struct {
	// RepoRoot is the absolute path to the module root (the dir with go.mod).
	RepoRoot string
	// MakeTarget is the make target quoted in the generated-file banner.
	MakeTarget string

	// tracked is the set of git-tracked files, keyed by repo-relative slash
	// path.
	tracked map[string]bool

	// ignored is the set of gitignored files (git ls-files --others --ignored),
	// keyed by repo-relative slash path. This — not "untracked" — is the source
	// of truth for "what to exclude": the module carries ~200 gitignored session
	// dirs under internal/cli/*/sessions and internal/cli/*/automode/sessions
	// that are not real code and must never appear in generated inventory. A
	// brand-new, not-yet-committed source file (e.g. a package doc.go) is
	// untracked but NOT ignored, so it must still be included — filtering on
	// "tracked" instead would make a dirty working tree silently drop whole
	// packages from the generated inventory.
	ignored map[string]bool

	pkgsOnce sync.Once
	pkgs     []*packages.Package
	pkgsErr  error
}

// newGenConfig resolves the repo root, reads the git-tracked file set, and
// returns a ready config. It does not load packages; that happens lazily on the
// first Packages call so subcommands that do not need the type graph (the CLI
// generator walks cobra directly) stay fast.
func newGenConfig(repoRootFlag, makeTarget string) (*genConfig, error) {
	root, err := resolveRepoRoot(repoRootFlag)
	if err != nil {
		return nil, err
	}
	tracked, err := loadTrackedFiles(root)
	if err != nil {
		return nil, err
	}
	ignored, err := loadIgnoredFiles(root)
	if err != nil {
		return nil, err
	}
	return &genConfig{RepoRoot: root, MakeTarget: makeTarget, tracked: tracked, ignored: ignored}, nil
}

// Tracked reports whether a repo-relative slash path is tracked by git.
func (c *genConfig) Tracked(relSlashPath string) bool {
	return c.tracked[relSlashPath]
}

// Ignored reports whether a repo-relative slash path is gitignored. Generators
// include a source file unless it is Ignored — so a not-yet-committed file
// counts, but a gitignored session-dir file never does.
func (c *genConfig) Ignored(relSlashPath string) bool {
	return c.ignored[relSlashPath]
}

// TrackedGoFiles returns every git-tracked .go file as a sorted slice of
// repo-relative slash paths. Test files are included; callers that want only
// production source should filter on the _test.go suffix.
func (c *genConfig) TrackedGoFiles() []string {
	var out []string
	for p := range c.tracked {
		if strings.HasSuffix(p, ".go") {
			out = append(out, p)
		}
	}
	sort.Strings(out)
	return out
}

// Packages loads "./..." with full type information, filtered to git-tracked
// first-party packages and sorted by import path. The result is memoized: the
// first call pays the load, subsequent calls (and other generators in the same
// process) reuse it. Ranging the returned slice is deterministic because it is
// pre-sorted; generators must still sort any per-package collections they build
// (Go randomizes map iteration).
func (c *genConfig) Packages() ([]*packages.Package, error) {
	c.pkgsOnce.Do(func() {
		c.pkgs, c.pkgsErr = loadPackages(c.RepoRoot, c.ignored)
	})
	return c.pkgs, c.pkgsErr
}

// resolveRepoRoot turns a flag value into the absolute module root by walking
// up from it until a go.mod is found. Callers normally pass ".", so this
// resolves the module root regardless of the process working directory.
func resolveRepoRoot(flagVal string) (string, error) {
	abs, err := filepath.Abs(flagVal)
	if err != nil {
		return "", fmt.Errorf("resolve repo root: %w", err)
	}
	for dir := abs; ; {
		if info, statErr := os.Stat(filepath.Join(dir, "go.mod")); statErr == nil && !info.IsDir() {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("resolve repo root: no go.mod found at or above %s", abs)
		}
		dir = parent
	}
}

// loadTrackedFiles runs `git ls-files` at root and returns the tracked file set
// keyed by repo-relative slash path. Using -z (NUL-delimited) keeps the parse
// deterministic and correct for paths with unusual characters.
func loadTrackedFiles(root string) (map[string]bool, error) {
	cmd := exec.Command("git", "ls-files", "-z")
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("git ls-files in %s: %w", root, err)
	}
	set := make(map[string]bool)
	for _, p := range strings.Split(string(out), "\x00") {
		if p != "" {
			set[p] = true
		}
	}
	if len(set) == 0 {
		return nil, fmt.Errorf("git ls-files in %s: no tracked files", root)
	}
	return set, nil
}

// loadIgnoredFiles runs `git ls-files --others --ignored --exclude-standard` at
// root and returns the gitignored file set keyed by repo-relative slash path.
// These are the ~200 session dirs and other build detritus that must never
// appear in generated inventory. An empty result is legitimate (a clean, fully
// committed checkout has nothing ignored on disk), so unlike loadTrackedFiles
// this does not treat emptiness as an error.
func loadIgnoredFiles(root string) (map[string]bool, error) {
	cmd := exec.Command("git", "ls-files", "--others", "--ignored", "--exclude-standard", "-z")
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("git ls-files --ignored in %s: %w", root, err)
	}
	set := make(map[string]bool)
	for _, p := range strings.Split(string(out), "\x00") {
		if p != "" {
			set[p] = true
		}
	}
	return set, nil
}

// loadPackages loads the module's first-party packages with full type info and
// drops any package that contains a GITIGNORED source file — that is how the
// gitignored session dirs are excluded. It filters on "ignored" rather than
// "not tracked" so a package carrying a brand-new, not-yet-committed file (a
// freshly added doc.go) is still included; filtering on tracked would let a
// dirty working tree silently drop whole packages. The result is sorted by
// import path.
func loadPackages(root string, ignored map[string]bool) ([]*packages.Package, error) {
	cfg := &packages.Config{Mode: loadMode, Dir: root, Tests: false}
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return nil, fmt.Errorf("load packages: %w", err)
	}
	kept := make([]*packages.Package, 0, len(pkgs))
	for _, p := range pkgs {
		if len(p.GoFiles) > 0 && !anyIgnored(p.GoFiles, root, ignored) {
			kept = append(kept, p)
		}
	}
	sort.Slice(kept, func(i, j int) bool { return kept[i].PkgPath < kept[j].PkgPath })
	return kept, nil
}

// anyIgnored reports whether any absolute file path is gitignored. A single
// gitignored file (a session dir) disqualifies the whole package.
func anyIgnored(absFiles []string, root string, ignored map[string]bool) bool {
	for _, f := range absFiles {
		rel, err := filepath.Rel(root, f)
		if err != nil || ignored[filepath.ToSlash(rel)] {
			return true
		}
	}
	return false
}

// generatedHeader builds the do-not-edit banner prepended to every doc.
// sourceNote is a one-line description of what the body is derived from.
func generatedHeader(sourceNote, makeTarget string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "<!-- %s -->\n", genBanner)
	if sourceNote != "" {
		fmt.Fprintf(&b, "<!-- %s -->\n", sourceNote)
	}
	fmt.Fprintf(&b, "<!-- Regenerate with: make %s -->\n", makeTarget)
	return b.String()
}

// readPreamble returns the checked-in prose partial for a doc, or "" when none
// exists. Preambles are optional (docs/reference/<name>.preamble.md): parsers
// own inventory, humans own rationale, and not every doc needs the latter. A
// genuinely unreadable file (permissions, etc.) is a hard error so a preamble
// is never silently dropped.
func readPreamble(root, name string) (string, error) {
	path := filepath.Join(root, refDir, name+".preamble.md")
	b, err := os.ReadFile(path) //nolint:gosec // G304: path is refDir + a known doc name
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return "", nil
		}
		return "", fmt.Errorf("read preamble %s: %w", path, err)
	}
	return string(b), nil
}

// assembleDoc joins the banner, optional preamble, and generated body into the
// final document: blank-line-separated sections with exactly one trailing
// newline. Trimming each section keeps output byte-stable regardless of how the
// preamble file happens to end.
func assembleDoc(header, preamble, body string) string {
	sections := []string{strings.TrimRight(header, "\n")}
	if p := strings.TrimSpace(preamble); p != "" {
		sections = append(sections, p)
	}
	if b := strings.Trim(body, "\n"); strings.TrimSpace(b) != "" {
		sections = append(sections, b)
	}
	return strings.Join(sections, "\n\n") + "\n"
}

// writeDoc writes content to path, creating the parent directory and ensuring
// exactly one trailing newline. Deterministic: the same content always yields
// the same bytes on disk, which is what the staleness gate diffs against.
func writeDoc(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil { //nolint:gosec // G306: reference docs are world-readable by design
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
