package registry

import (
	"bytes"
	"strings"
	"testing"
)

func TestRecorderOmitsCoverageWhenExecutableTestFails(t *testing.T) {
	t.Parallel()
	recorder := coverageRecorder{}
	failed := &recordingTest{name: "TestFailedScenario", failed: true}

	recorder.covers(failed, validScenario())
	failed.runCleanups()

	if scenarios := recorder.snapshot(); len(scenarios) != 0 {
		t.Fatalf("recorded failed scenarios = %d, want 0", len(scenarios))
	}
}

func TestRecorderGeneratesVersionedOwningReport(t *testing.T) {
	t.Parallel()
	recorder := coverageRecorder{}
	scenario := validScenario()
	scenario.Test = "TestExactRoundTrip"
	if err := recorder.record(scenario); err != nil {
		t.Fatal(err)
	}

	report, err := recorder.report("loom-sha")
	if err != nil {
		t.Fatal(err)
	}
	if report.SchemaVersion != SchemaVersion || report.Repository != RepositoryLoom || report.Revision != "loom-sha" {
		t.Fatalf("report identity = %#v", report)
	}
	if len(report.Cases) != 1 || report.Cases[0].ID != 1 || report.Cases[0].Test != "TestExactRoundTrip" {
		t.Fatalf("report cases = %#v", report.Cases)
	}

	var output bytes.Buffer
	if err := WriteYAML(&output, report); err != nil {
		t.Fatal(err)
	}
	written := output.String()
	for _, literal := range []string{
		"# Code generated by skills edge coverage; DO NOT EDIT.",
		"schema_version: skills-edge-coverage/v1",
		"repository: loom",
		"revision: loom-sha",
		"test: TestExactRoundTrip",
	} {
		if !strings.Contains(written, literal) {
			t.Fatalf("generated report omitted %q:\n%s", literal, written)
		}
	}
}

func TestValidateReportAcceptsPartialOwningRepoCoverage(t *testing.T) {
	t.Parallel()
	report := Report{
		SchemaVersion: SchemaVersion, Repository: RepositoryLoom, Revision: "7391ab8a",
		Cases: []CaseCoverage{{
			ID: 1, Behavior: "binary bundled files survive import and materialization",
			Owner: OwnerLoom, Seam: SeamLoomFleetE2E,
			Test:     "TestSkillUpdateSelectsAndMaterializesExactRevision",
			Backends: []string{"redis"}, Providers: []string{"minio"},
		}},
	}
	if err := ValidateReport(report); err != nil {
		t.Fatalf("ValidateReport() error = %v", err)
	}
}

func TestValidateReportRejectsInvalidEntries(t *testing.T) {
	t.Parallel()
	valid := validReport()
	tests := []struct {
		name    string
		mutate  func(Report) Report
		wantErr string
	}{
		{"wrong schema", func(r Report) Report { r.SchemaVersion = "v0"; return r }, "unsupported schema_version"},
		{"missing revision", func(r Report) Report { r.Revision = ""; return r }, "revision is required"},
		{"duplicate", func(r Report) Report { r.Cases = append(r.Cases, r.Cases[0]); return r }, "duplicate edge-case ID 1"},
		{"below range", func(r Report) Report { r.Cases[0].ID = 0; return r }, "edge-case ID 0 is outside 1-95"},
		{"above range", func(r Report) Report { r.Cases[0].ID = 96; return r }, "edge-case ID 96 is outside 1-95"},
		{"invalid seam", func(r Report) Report { r.Cases[0].Seam = "invented"; return r }, "invalid seam"},
		{"missing executable test", func(r Report) Report { r.Cases[0].Test = ""; return r }, "test is required"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			err := ValidateReport(tt.mutate(cloneReport(valid)))
			if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
				t.Fatalf("ValidateReport() error = %v, want %q", err, tt.wantErr)
			}
		})
	}
}

func TestValidateReadyRequiresExactOneToNinetyFiveUnion(t *testing.T) {
	t.Parallel()
	reports, exclusions := completeReadyInputs()
	if err := ValidateReady(reports, exclusions); err != nil {
		t.Fatalf("ValidateReady() error = %v", err)
	}

	t.Run("missing", func(t *testing.T) {
		reports, exclusions := completeReadyInputs()
		reports[0].Cases = reports[0].Cases[1:]
		err := ValidateReady(reports, exclusions)
		if err == nil || !strings.Contains(err.Error(), "missing edge-case IDs: 1") {
			t.Fatalf("ValidateReady() error = %v, want missing ID 1", err)
		}
	})
	t.Run("duplicate across repositories", func(t *testing.T) {
		reports, exclusions := completeReadyInputs()
		duplicate := reports[0].Cases[0]
		duplicate.Owner, duplicate.Seam = OwnerFleet, SeamFleetDomain
		reports[1].Cases = append(reports[1].Cases, duplicate)
		err := ValidateReady(reports, exclusions)
		if err == nil || !strings.Contains(err.Error(), "duplicate edge-case ID 1") {
			t.Fatalf("ValidateReady() error = %v, want duplicate ID 1", err)
		}
	})
	t.Run("duplicate report and exclusion", func(t *testing.T) {
		reports, exclusions := completeReadyInputs()
		reports[0].Cases = append(reports[0].Cases, CaseCoverage{
			ID: 72, Behavior: "legacy migration", Owner: OwnerLoom,
			Seam: SeamReleaseCI, Test: "TestNoLegacyMigration",
		})
		err := ValidateReady(reports, exclusions)
		if err == nil || !strings.Contains(err.Error(), "duplicate edge-case ID 72") {
			t.Fatalf("ValidateReady() error = %v, want duplicate ID 72", err)
		}
	})
}

func TestValidateReadyAcceptsOnlyStrictCutoverExclusions(t *testing.T) {
	t.Parallel()
	reports, exclusions := completeReadyInputs()
	for reportIndex := range reports {
		filtered := reports[reportIndex].Cases[:0]
		for _, coverage := range reports[reportIndex].Cases {
			if coverage.ID != 71 {
				filtered = append(filtered, coverage)
			}
		}
		reports[reportIndex].Cases = filtered
	}
	exclusions[0].ID = 71
	err := ValidateReady(reports, exclusions)
	if err == nil || !strings.Contains(err.Error(), "edge-case ID 71 cannot be excluded") {
		t.Fatalf("ValidateReady() error = %v, want invalid exclusion", err)
	}
}

func validReport() Report {
	return Report{
		SchemaVersion: SchemaVersion, Repository: RepositoryLoom, Revision: "revision",
		Cases: []CaseCoverage{{ID: 1, Behavior: "behavior", Owner: OwnerLoom, Seam: SeamLoomDomain, Test: "TestBehavior"}},
	}
}

func completeReadyInputs() ([]Report, []Exclusion) {
	loom := Report{SchemaVersion: SchemaVersion, Repository: RepositoryLoom, Revision: "loom-sha"}
	fleet := Report{SchemaVersion: SchemaVersion, Repository: RepositoryFleet, Revision: "fleet-sha"}
	for id := MinEdgeCaseID; id <= MaxEdgeCaseID; id++ {
		if id >= FirstStrictCutoverExclusionID && id <= LastStrictCutoverExclusionID {
			continue
		}
		coverage := CaseCoverage{ID: id, Behavior: "behavior", Seam: SeamLoomDomain, Test: "TestBehavior"}
		if id%2 == 0 {
			coverage.Owner, coverage.Seam = OwnerFleet, SeamFleetDomain
			fleet.Cases = append(fleet.Cases, coverage)
		} else {
			coverage.Owner = OwnerLoom
			loom.Cases = append(loom.Cases, coverage)
		}
	}
	exclusions := make([]Exclusion, 0, 6)
	for id := FirstStrictCutoverExclusionID; id <= LastStrictCutoverExclusionID; id++ {
		exclusions = append(exclusions, Exclusion{
			ID: id, Decision: StrictCutoverNoMigration,
			Rationale: "Fleet-backed Skills are unlaunched; obsolete development data is recreated.",
		})
	}
	return []Report{loom, fleet}, exclusions
}

func cloneReport(report Report) Report {
	out := report
	out.Cases = append([]CaseCoverage(nil), report.Cases...)
	return out
}

func validScenario() Scenario {
	return Scenario{
		ID: "exact-round-trip", Behavior: "files round-trip exactly",
		Owner: OwnerLoom, Seam: SeamLoomFleetE2E,
		Backends: []string{"redis"}, Providers: []string{"minio"},
		Cases: []EdgeCase{{
			ID: 1, Behavior: "binary files round-trip byte-for-byte",
			Rationale: "the executable test compares independent literal bytes",
		}},
	}
}

type recordingTest struct {
	name     string
	failed   bool
	cleanups []func()
}

func (t *recordingTest) Helper()                {}
func (t *recordingTest) Name() string           { return t.name }
func (t *recordingTest) Failed() bool           { return t.failed }
func (t *recordingTest) Cleanup(cleanup func()) { t.cleanups = append(t.cleanups, cleanup) }
func (t *recordingTest) Fatalf(string, ...any)  { panic("unexpected Fatalf") }
func (t *recordingTest) Errorf(string, ...any)  { panic("unexpected Errorf") }
func (t *recordingTest) runCleanups() {
	for index := len(t.cleanups) - 1; index >= 0; index-- {
		t.cleanups[index]()
	}
}
