package registry

import (
	"bytes"
	"strings"
	"testing"
)

func TestScenariosAreValid(t *testing.T) {
	if err := Validate(Scenarios); err != nil {
		t.Fatal(err)
	}
}

func TestValidateRejectsDuplicateEdgeCaseOwnership(t *testing.T) {
	scenarios := []Scenario{
		{ID: "one", Behavior: "one", Test: "TestOne", Owner: "loom", Seam: "loom-fleet-e2e", Backends: []string{"redis"}, Providers: []string{"minio"}, Status: "covered", Cases: []EdgeCase{{ID: 1, Behavior: "first", Rationale: "first"}}},
		{ID: "two", Behavior: "two", Test: "TestTwo", Owner: "loom", Seam: "loom-fleet-e2e", Backends: []string{"redis"}, Providers: []string{"minio"}, Status: "covered", Cases: []EdgeCase{{ID: 1, Behavior: "second", Rationale: "second"}}},
	}

	err := Validate(scenarios)
	if err == nil || !strings.Contains(err.Error(), "edge case 1") || !strings.Contains(err.Error(), "one") || !strings.Contains(err.Error(), "two") {
		t.Fatalf("Validate error = %v, want duplicate edge-case ownership", err)
	}
}

func TestWriteYAMLReportsEveryExecutableScenario(t *testing.T) {
	var output bytes.Buffer
	if err := WriteYAML(&output, Scenarios); err != nil {
		t.Fatal(err)
	}

	report := output.String()
	for _, scenario := range Scenarios {
		if !strings.Contains(report, "id: "+scenario.ID) || !strings.Contains(report, "test: "+scenario.Test) {
			t.Fatalf("generated report omitted scenario %q or test %q\n%s", scenario.ID, scenario.Test, report)
		}
	}
	if !strings.HasPrefix(report, "# Code generated by e2e-coverage; DO NOT EDIT.\nversion: 1\n") {
		t.Fatalf("generated report header is not stable:\n%s", report)
	}
}
