// Package registry validates E2E coverage declared beside executable tests and
// renders reports from the scenarios recorded by the current test process.
package registry

import (
	"fmt"
	"io"
	"os"
	"regexp"
	"slices"
	"strings"
	"sync"
	"testing"

	"gopkg.in/yaml.v3"
)

var scenarioIDPattern = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)

var executedCoverage coverageRecorder

type coverageRecorder struct {
	mu        sync.Mutex
	scenarios []Scenario
}

type EdgeCase struct {
	ID        int    `yaml:"id"`
	Behavior  string `yaml:"behavior"`
	Rationale string `yaml:"rationale"`
}

type Scenario struct {
	ID        string     `yaml:"id"`
	Behavior  string     `yaml:"behavior"`
	Test      string     `yaml:"test"`
	Owner     string     `yaml:"owner"`
	Seam      string     `yaml:"seam"`
	Backends  []string   `yaml:"backends"`
	Providers []string   `yaml:"providers"`
	Status    string     `yaml:"status"`
	Cases     []EdgeCase `yaml:"cases,omitempty"`
}

// Covers binds authored coverage metadata to the executable top-level test.
// It records no product behavior and does not hide any public Loom operation.
func (s Scenario) Covers(t *testing.T) {
	t.Helper()
	executedCoverage.covers(t, s)
}

func (r *coverageRecorder) covers(t *testing.T, scenario Scenario) {
	t.Helper()
	scenario.Test = t.Name()
	scenario.Status = "covered"
	if err := validateScenario(scenario); err != nil {
		t.Fatalf("invalid scenario %q: %v", scenario.ID, err)
	}

	r.mu.Lock()
	defer r.mu.Unlock()
	updated := append(slices.Clone(r.scenarios), scenario)
	if err := Validate(updated); err != nil {
		t.Fatalf("record E2E coverage: %v", err)
	}
	r.scenarios = updated
}

func (r *coverageRecorder) snapshot() []Scenario {
	r.mu.Lock()
	defer r.mu.Unlock()
	return slices.Clone(r.scenarios)
}

func (r *coverageRecorder) writeYAML(w io.Writer) error {
	scenarios := r.snapshot()
	if len(scenarios) == 0 {
		return fmt.Errorf("no E2E scenarios executed")
	}
	return WriteYAML(w, scenarios)
}

// WriteCoverageFile renders coverage recorded by the current E2E test process.
func WriteCoverageFile(path string) error {
	var report strings.Builder
	if err := executedCoverage.writeYAML(&report); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(report.String()), 0o644)
}

func Validate(scenarios []Scenario) error {
	seenScenarios := make(map[string]struct{}, len(scenarios))
	caseOwners := make(map[int]string)
	for _, scenario := range scenarios {
		if err := validateScenario(scenario); err != nil {
			return fmt.Errorf("scenario %q: %w", scenario.ID, err)
		}
		if _, duplicate := seenScenarios[scenario.ID]; duplicate {
			return fmt.Errorf("duplicate scenario id %q", scenario.ID)
		}
		seenScenarios[scenario.ID] = struct{}{}
		for _, edgeCase := range scenario.Cases {
			if owner, duplicate := caseOwners[edgeCase.ID]; duplicate {
				return fmt.Errorf("edge case %d is owned by both %q and %q", edgeCase.ID, owner, scenario.ID)
			}
			caseOwners[edgeCase.ID] = scenario.ID
		}
	}
	return nil
}

func validateScenario(s Scenario) error {
	if !scenarioIDPattern.MatchString(s.ID) {
		return fmt.Errorf("id must be lowercase kebab-case")
	}
	if strings.TrimSpace(s.Behavior) == "" {
		return fmt.Errorf("behavior is required")
	}
	if !strings.HasPrefix(s.Test, "Test") {
		return fmt.Errorf("top-level Go test is required")
	}
	if strings.TrimSpace(s.Owner) == "" || strings.TrimSpace(s.Seam) == "" {
		return fmt.Errorf("owner and seam are required")
	}
	if s.Status != "covered" {
		return fmt.Errorf("executable scenario status must be covered")
	}
	if err := validateDimension("backend", s.Backends, map[string]bool{"redis": true, "postgres": true}); err != nil {
		return err
	}
	if err := validateDimension("provider", s.Providers, map[string]bool{"local": true, "minio": true, "gcs": true}); err != nil {
		return err
	}
	seenCases := make(map[int]struct{}, len(s.Cases))
	for _, edgeCase := range s.Cases {
		if edgeCase.ID <= 0 || strings.TrimSpace(edgeCase.Behavior) == "" || strings.TrimSpace(edgeCase.Rationale) == "" {
			return fmt.Errorf("edge case id, behavior, and rationale are required")
		}
		if _, duplicate := seenCases[edgeCase.ID]; duplicate {
			return fmt.Errorf("duplicate edge case %d", edgeCase.ID)
		}
		seenCases[edgeCase.ID] = struct{}{}
	}
	return nil
}

func validateDimension(label string, values []string, allowed map[string]bool) error {
	if len(values) == 0 {
		return fmt.Errorf("at least one %s is required", label)
	}
	seen := make(map[string]struct{}, len(values))
	for _, value := range values {
		if !allowed[value] {
			return fmt.Errorf("unknown %s %q", label, value)
		}
		if _, duplicate := seen[value]; duplicate {
			return fmt.Errorf("duplicate %s %q", label, value)
		}
		seen[value] = struct{}{}
	}
	return nil
}

func WriteYAML(w io.Writer, scenarios []Scenario) error {
	if err := Validate(scenarios); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "# Code generated by e2e-coverage; DO NOT EDIT.\n"); err != nil {
		return err
	}
	encoder := yaml.NewEncoder(w)
	encoder.SetIndent(2)
	defer encoder.Close()
	return encoder.Encode(struct {
		Version   int        `yaml:"version"`
		Scenarios []Scenario `yaml:"scenarios"`
	}{Version: 1, Scenarios: scenarios})
}
