package registry

import (
	"bytes"
	"strings"
	"testing"
)

func TestRecorderDerivesExecutionMetadata(t *testing.T) {
	recorder := coverageRecorder{}
	recorder.covers(t, Scenario{
		ID:        "adjacent-scenario",
		Behavior:  "coverage metadata lives beside its executable test",
		Owner:     "loom",
		Seam:      "loom-fleet-e2e",
		Backends:  []string{"redis"},
		Providers: []string{"minio"},
	})

	scenarios := recorder.snapshot()
	if len(scenarios) != 1 {
		t.Fatalf("recorded scenarios = %d, want 1", len(scenarios))
	}
	if scenarios[0].Test != t.Name() {
		t.Fatalf("recorded test = %q, want %q", scenarios[0].Test, t.Name())
	}
	if scenarios[0].Status != "covered" {
		t.Fatalf("recorded status = %q, want covered", scenarios[0].Status)
	}
}

func TestRecorderWritesOnlyExecutedCoverage(t *testing.T) {
	recorder := coverageRecorder{}
	recorder.covers(t, Scenario{
		ID:        "executed-scenario",
		Behavior:  "the report is produced by the executable test run",
		Owner:     "loom",
		Seam:      "loom-fleet-e2e",
		Backends:  []string{"redis"},
		Providers: []string{"minio"},
	})

	var output bytes.Buffer
	if err := recorder.writeYAML(&output); err != nil {
		t.Fatal(err)
	}
	report := output.String()
	if !strings.Contains(report, "id: executed-scenario") || !strings.Contains(report, "test: "+t.Name()) {
		t.Fatalf("generated report omitted executed coverage:\n%s", report)
	}
	if !strings.HasPrefix(report, "# Code generated by e2e-coverage; DO NOT EDIT.\nversion: 1\n") {
		t.Fatalf("generated report header is not stable:\n%s", report)
	}
}

func TestValidateRejectsDuplicateEdgeCaseOwnership(t *testing.T) {
	scenarios := []Scenario{
		{ID: "one", Behavior: "one", Test: "TestOne", Owner: "loom", Seam: "loom-fleet-e2e", Backends: []string{"redis"}, Providers: []string{"minio"}, Status: "covered", Cases: []EdgeCase{{ID: 1, Behavior: "first", Rationale: "first"}}},
		{ID: "two", Behavior: "two", Test: "TestTwo", Owner: "loom", Seam: "loom-fleet-e2e", Backends: []string{"redis"}, Providers: []string{"minio"}, Status: "covered", Cases: []EdgeCase{{ID: 1, Behavior: "second", Rationale: "second"}}},
	}

	err := Validate(scenarios)
	if err == nil || !strings.Contains(err.Error(), "edge case 1") || !strings.Contains(err.Error(), "one") || !strings.Contains(err.Error(), "two") {
		t.Fatalf("Validate error = %v, want duplicate edge-case ownership", err)
	}
}
