#!/usr/bin/env bash
# check-package-size_test.sh - Tests for check-package-size.sh
#
# Creates a fake repo structure in a temp dir, copies the script into it,
# and verifies counting and threshold behavior.
#
# Usage: ./scripts/check-package-size_test.sh
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PASS_COUNT=0
FAIL_COUNT=0

pass() {
    echo "PASS: $1"
    PASS_COUNT=$((PASS_COUNT + 1))
}

fail() {
    echo "FAIL: $1"
    FAIL_COUNT=$((FAIL_COUNT + 1))
}

# ---------------------------------------------------------------------------
# Setup: create a temporary fake repo structure
# ---------------------------------------------------------------------------
TEST_TMPDIR=$(mktemp -d)

cleanup() {
    rm -rf "$TEST_TMPDIR"
}
trap cleanup EXIT

# The script resolves REPO_ROOT from SCRIPT_DIR/.., so we need:
#   $TEST_TMPDIR/repo/scripts/check-package-size.sh
#   $TEST_TMPDIR/repo/internal/<packages>
FAKE_REPO="$TEST_TMPDIR/repo"
FAKE_SCRIPTS="$FAKE_REPO/scripts"
mkdir -p "$FAKE_SCRIPTS"

cp "$SCRIPT_DIR/check-package-size.sh" "$FAKE_SCRIPTS/check-package-size.sh"
chmod +x "$FAKE_SCRIPTS/check-package-size.sh"

SCRIPT_UNDER_TEST="$FAKE_SCRIPTS/check-package-size.sh"

# Helper: create N fake .go files in a package directory.
make_package() {
    local pkg_path="$1"
    local num_files="$2"
    local full_path="$FAKE_REPO/$pkg_path"
    mkdir -p "$full_path"
    for ((i = 1; i <= num_files; i++)); do
        echo "package $(basename "$pkg_path")" > "$full_path/file_$i.go"
    done
}

# Helper: create a generated code .go file.
make_generated_file() {
    local file_path="$1"
    local full_path="$FAKE_REPO/$file_path"
    mkdir -p "$(dirname "$full_path")"
    printf '// Code generated by stringer; DO NOT EDIT.\npackage foo\n' > "$full_path"
}

# Helper: create a test .go file.
make_test_file() {
    local file_path="$1"
    local full_path="$FAKE_REPO/$file_path"
    mkdir -p "$(dirname "$full_path")"
    echo "package foo" > "$full_path"
}

# Helper: reset fake repo internal/ directory.
reset_repo() {
    rm -rf "$FAKE_REPO/internal"
}

# ---------------------------------------------------------------------------
# Test 1: All packages under threshold → exit 0
# ---------------------------------------------------------------------------
test_under_threshold() {
    reset_repo
    make_package "internal/alpha" 5
    make_package "internal/beta" 10
    make_package "internal/gamma" 3

    local output exit_code
    output=$("$SCRIPT_UNDER_TEST" 25 2>&1) && exit_code=0 || exit_code=$?

    if [[ "$exit_code" -eq 0 ]]; then
        pass "Under threshold: exit 0"
    else
        fail "Under threshold should exit 0, got $exit_code. Output: $output"
    fi
}

# ---------------------------------------------------------------------------
# Test 2: One package over threshold → exit 1 with output
# ---------------------------------------------------------------------------
test_one_over_threshold() {
    reset_repo
    make_package "internal/big" 30
    make_package "internal/small" 5

    local output exit_code
    output=$("$SCRIPT_UNDER_TEST" 25 2>&1) && exit_code=0 || exit_code=$?

    if [[ "$exit_code" -eq 1 ]]; then
        pass "One over threshold: exit 1"
    else
        fail "One over threshold should exit 1, got $exit_code. Output: $output"
        return
    fi

    if echo "$output" | grep -q "internal/big"; then
        pass "One over threshold: output lists offending package"
    else
        fail "One over threshold: output should list internal/big. Got: $output"
    fi

    if echo "$output" | grep -q "30"; then
        pass "One over threshold: output shows count"
    else
        fail "One over threshold: output should show count 30. Got: $output"
    fi
}

# ---------------------------------------------------------------------------
# Test 3: Multiple violations → all listed, sorted descending
# ---------------------------------------------------------------------------
test_multiple_violations() {
    reset_repo
    make_package "internal/huge" 50
    make_package "internal/big" 30
    make_package "internal/small" 5

    local output exit_code
    output=$("$SCRIPT_UNDER_TEST" 25 2>&1) && exit_code=0 || exit_code=$?

    if [[ "$exit_code" -eq 1 ]]; then
        pass "Multiple violations: exit 1"
    else
        fail "Multiple violations should exit 1, got $exit_code. Output: $output"
        return
    fi

    # Check both packages are listed.
    if echo "$output" | grep -q "internal/huge" && echo "$output" | grep -q "internal/big"; then
        pass "Multiple violations: both packages listed"
    else
        fail "Multiple violations should list both packages. Got: $output"
        return
    fi

    # Verify sorted descending: huge (50) should appear before big (30).
    local huge_line big_line
    huge_line=$(echo "$output" | grep -n "internal/huge" | head -1 | cut -d: -f1)
    big_line=$(echo "$output" | grep -n "internal/big" | head -1 | cut -d: -f1)
    if [[ "$huge_line" -lt "$big_line" ]]; then
        pass "Multiple violations: sorted descending by count"
    else
        fail "Multiple violations: should be sorted descending. huge line=$huge_line, big line=$big_line"
    fi
}

# ---------------------------------------------------------------------------
# Test 4: Custom threshold via $1
# ---------------------------------------------------------------------------
test_custom_threshold() {
    reset_repo
    make_package "internal/pkg" 5

    local output exit_code
    output=$("$SCRIPT_UNDER_TEST" 3 2>&1) && exit_code=0 || exit_code=$?

    if [[ "$exit_code" -eq 1 ]]; then
        pass "Custom threshold (3): 5-file package fails"
    else
        fail "Custom threshold (3): 5-file package should fail, got $exit_code. Output: $output"
    fi
}

# ---------------------------------------------------------------------------
# Test 5: Test files excluded
# ---------------------------------------------------------------------------
test_test_files_excluded() {
    reset_repo
    make_package "internal/pkg" 20
    # Add 10 test files — should NOT count toward the limit.
    for ((i = 1; i <= 10; i++)); do
        make_test_file "internal/pkg/file_${i}_test.go"
    done

    local output exit_code
    output=$("$SCRIPT_UNDER_TEST" 25 2>&1) && exit_code=0 || exit_code=$?

    if [[ "$exit_code" -eq 0 ]]; then
        pass "Test files excluded: 20 source + 10 test under threshold 25"
    else
        fail "Test files excluded: should pass with 20 source files, got $exit_code. Output: $output"
    fi
}

# ---------------------------------------------------------------------------
# Test 6: Generated code excluded
# ---------------------------------------------------------------------------
test_generated_code_excluded() {
    reset_repo
    make_package "internal/pkg" 20
    # Add 10 generated files — should NOT count toward the limit.
    for ((i = 1; i <= 10; i++)); do
        make_generated_file "internal/pkg/gen_$i.go"
    done

    local output exit_code
    output=$("$SCRIPT_UNDER_TEST" 25 2>&1) && exit_code=0 || exit_code=$?

    if [[ "$exit_code" -eq 0 ]]; then
        pass "Generated code excluded: 20 source + 10 generated under threshold 25"
    else
        fail "Generated code excluded: should pass with 20 source files, got $exit_code. Output: $output"
    fi
}

# ---------------------------------------------------------------------------
# Test 7: Invalid threshold → exit 2
# ---------------------------------------------------------------------------
test_invalid_threshold() {
    reset_repo
    make_package "internal/pkg" 5

    local output exit_code
    output=$("$SCRIPT_UNDER_TEST" abc 2>&1) && exit_code=0 || exit_code=$?

    if [[ "$exit_code" -eq 2 ]]; then
        pass "Invalid threshold: exit 2"
    else
        fail "Invalid threshold should exit 2, got $exit_code. Output: $output"
    fi
}

# ---------------------------------------------------------------------------
# Test 8: Exactly at threshold → exit 0 (boundary check: > not >=)
# ---------------------------------------------------------------------------
test_exactly_at_threshold() {
    reset_repo
    make_package "internal/pkg" 25

    local output exit_code
    output=$("$SCRIPT_UNDER_TEST" 25 2>&1) && exit_code=0 || exit_code=$?

    if [[ "$exit_code" -eq 0 ]]; then
        pass "Exactly at threshold (25 files): exit 0"
    else
        fail "Exactly at threshold should exit 0, got $exit_code. Output: $output"
    fi
}

# ---------------------------------------------------------------------------
# Test 9: Default threshold (no argument) uses 25
# ---------------------------------------------------------------------------
test_default_threshold() {
    reset_repo
    make_package "internal/pkg" 26

    local output exit_code
    output=$("$SCRIPT_UNDER_TEST" 2>&1) && exit_code=0 || exit_code=$?

    if [[ "$exit_code" -eq 1 ]]; then
        pass "Default threshold: 26-file package fails with no arg"
    else
        fail "Default threshold: 26-file package should fail, got $exit_code. Output: $output"
    fi
}

# ---------------------------------------------------------------------------
# Run all tests
# ---------------------------------------------------------------------------

echo "=== check-package-size.sh test suite ==="
echo ""

test_under_threshold
test_one_over_threshold
test_multiple_violations
test_custom_threshold
test_test_files_excluded
test_generated_code_excluded
test_invalid_threshold
test_exactly_at_threshold
test_default_threshold

echo ""
echo "=== Results: $PASS_COUNT passed, $FAIL_COUNT failed ==="

if [[ "$FAIL_COUNT" -gt 0 ]]; then
    exit 1
fi
