#!/usr/bin/env bash
set -euo pipefail

unset LOOM_WORKSPACE
unset LOOM_WORKSPACE_RUNTIME_DIR
unset LOOM_CONFIG_DIR
unset LOOM_DESKTOP_DATA_DIR
unset LOOM_FRONTEND_DIR
unset LOOM_WEBUI_URL
unset LOOM_LOCAL_RUNTIME
unset LOOM_AGENT_NAME
unset LOOM_AGENT_ROLE
unset LOOM_AGENT_TERMINAL_ID
unset LOOM_SESSION_ID
unset LOOM_ORCHESTRATOR_SESSION_ID

exec "$@"
