// Code generated by task-contract-gen from FleetDB api/openapi.yaml; DO NOT EDIT.
// Contract SHA256: 3db2b9301f434971aeb313d0f4dc6e24893075fdbab9d0c6a885988811d00418

export type TaskRunExecutionClass = "correction" | "implementation" | "review";
export type TaskRunRootState = "failed" | "pending" | "provisioning" | "ready" | "released" | "retained";
export type TaskChangePublicationStatus = "confirmed";

export interface TaskRun {
  workspace_key?: string;
  task_run_id: string;
  driver_run_id?: string;
  driver_step_id?: string;
  task_id: string;
  execution_class: TaskRunExecutionClass;
  repository_set: string[];
  change_set_version?: number;
  root_generation: number;
  root_state: TaskRunRootState;
  root_node_id?: string;
  root_fencing_token: number;
  backend_kind?: string;
  backend_session_ref?: string;
  worker_profile_id?: string;
  runner?: string;
  runner_ref?: string;
  runner_kind?: string;
  runner_entrypoint?: string;
  runner_driver_version_id?: string;
  provider_profile?: string;
  status: string;
  node_id?: string;
  lease_id?: string;
  fencing_token?: number;
  runner_placement?: TaskRunPlacement;
  sandbox_placement?: TaskRunPlacement;
  [key: string]: unknown;
}

export interface TaskRunPlacement {
  provider?: string;
  node_id?: string;
  runner_id?: string;
  process_ref?: string;
  sandbox_id?: string;
  image_or_snapshot?: string;
  cwd?: string;
  repo_ref?: string;
  cleanup_policy?: string;
  egress_mode?: string;
  egress_mechanism?: string;
  started_at?: string;
  heartbeat_at?: string;
  retained_until?: string | null;
}

export interface TaskBranch {
  workspace_key: string;
  task_id: string;
  repo_name: string;
  branch_name: string;
  admitted_base_sha: string;
  expected_remote_head_sha?: string;
  confirmed_remote_head_sha?: string;
  created_at: string;
  updated_at: string;
}

export interface TaskChangeSetEntry {
  repo_name: string;
  base_sha: string;
  head_sha: string;
  branch_name: string;
  remote_name: string;
  publication_status: TaskChangePublicationStatus;
  artifact_refs: string[];
}

export interface TaskChangeSet {
  workspace_key: string;
  task_id: string;
  version: number;
  entries: TaskChangeSetEntry[];
  created_at: string;
}
