// Code generated by task-contract-gen from FleetDB api/openapi.yaml; DO NOT EDIT.
// Contract SHA256: 3db2b9301f434971aeb313d0f4dc6e24893075fdbab9d0c6a885988811d00418

package domain

import (
	"encoding/json"
	"time"
)

type TaskRunExecutionClass string

const (
	TaskRunExecutionImplementation TaskRunExecutionClass = "implementation"
	TaskRunExecutionReview         TaskRunExecutionClass = "review"
	TaskRunExecutionCorrection     TaskRunExecutionClass = "correction"
)

func (c TaskRunExecutionClass) IsValid() bool {
	switch c {
	case TaskRunExecutionImplementation, TaskRunExecutionReview, TaskRunExecutionCorrection:
		return true
	}
	return false
}

func (c TaskRunExecutionClass) IsWriter() bool {
	return c == TaskRunExecutionImplementation || c == TaskRunExecutionCorrection
}

type TaskRunRootState string

const (
	TaskRunRootPending      TaskRunRootState = "pending"
	TaskRunRootProvisioning TaskRunRootState = "provisioning"
	TaskRunRootReady        TaskRunRootState = "ready"
	TaskRunRootRetained     TaskRunRootState = "retained"
	TaskRunRootReleased     TaskRunRootState = "released"
	TaskRunRootFailed       TaskRunRootState = "failed"
)

func (s TaskRunRootState) IsValid() bool {
	switch s {
	case TaskRunRootPending, TaskRunRootProvisioning, TaskRunRootReady, TaskRunRootRetained, TaskRunRootReleased, TaskRunRootFailed:
		return true
	}
	return false
}

type TaskRunPlacement struct {
	Provider        string     `json:"provider,omitempty"`
	NodeID          string     `json:"node_id,omitempty"`
	RunnerID        string     `json:"runner_id,omitempty"`
	ProcessRef      string     `json:"process_ref,omitempty"`
	SandboxID       string     `json:"sandbox_id,omitempty"`
	ImageOrSnapshot string     `json:"image_or_snapshot,omitempty"`
	CWD             string     `json:"cwd,omitempty"`
	RepoRef         string     `json:"repo_ref,omitempty"`
	CleanupPolicy   string     `json:"cleanup_policy,omitempty"`
	EgressMode      string     `json:"egress_mode,omitempty"`
	EgressMechanism string     `json:"egress_mechanism,omitempty"`
	StartedAt       time.Time  `json:"started_at,omitempty"`
	HeartbeatAt     time.Time  `json:"heartbeat_at,omitempty"`
	RetainedUntil   *time.Time `json:"retained_until,omitempty"`
}

type TaskRun struct {
	WorkspaceKey      string                `json:"workspace_key"`
	TaskRunID         string                `json:"task_run_id"`
	DriverRunID       string                `json:"driver_run_id,omitempty"`
	DriverStepID      string                `json:"driver_step_id,omitempty"`
	TaskID            string                `json:"task_id"`
	ExecutionClass    TaskRunExecutionClass `json:"execution_class"`
	RepositorySet     []string              `json:"repository_set"`
	ChangeSetVersion  int                   `json:"change_set_version,omitempty"`
	RootGeneration    int64                 `json:"root_generation"`
	RootState         TaskRunRootState      `json:"root_state"`
	RootNodeID        string                `json:"root_node_id,omitempty"`
	RootFencingToken  int64                 `json:"root_fencing_token"`
	BackendKind       string                `json:"backend_kind,omitempty"`
	BackendSessionRef string                `json:"backend_session_ref,omitempty"`
	WorkerProfileID   string                `json:"worker_profile_id,omitempty"`
	Runner            string                `json:"runner,omitempty"`
	RunnerRef         string                `json:"runner_ref,omitempty"`
	RunnerKind        string                `json:"runner_kind,omitempty"`
	RunnerEntrypoint  string                `json:"runner_entrypoint,omitempty"`
	RunnerVersionID   string                `json:"runner_driver_version_id,omitempty"`
	ProviderProfile   string                `json:"provider_profile,omitempty"`
	Status            TaskRunStatus         `json:"status"`
	NodeID            string                `json:"node_id,omitempty"`
	LeaseID           string                `json:"lease_id,omitempty"`
	FencingToken      int64                 `json:"fencing_token,omitempty"`
	RunnerPlacement   TaskRunPlacement      `json:"runner_placement,omitempty"`
	SandboxPlacement  TaskRunPlacement      `json:"sandbox_placement,omitempty"`
	Input             json.RawMessage       `json:"input,omitempty"`
	ExitCode          *int                  `json:"exit_code,omitempty"`
	LogsRef           string                `json:"logs_ref,omitempty"`
	ArtifactsRef      string                `json:"artifacts_ref,omitempty"`
	InputTokens       int64                 `json:"input_tokens,omitempty"`
	OutputTokens      int64                 `json:"output_tokens,omitempty"`
	CacheReadTokens   int64                 `json:"cache_read_tokens,omitempty"`
	CacheWriteTokens  int64                 `json:"cache_write_tokens,omitempty"`
	EstimatedCostUSD  float64               `json:"estimated_cost_usd,omitempty"`
	RuntimeMetadata   map[string]string     `json:"runtime_metadata,omitempty"`
	NextEligibleAt    time.Time             `json:"next_eligible_at,omitempty"`
	StartedAt         time.Time             `json:"started_at,omitempty"`
	LastHeartbeat     time.Time             `json:"last_heartbeat,omitempty"`
	FinishedAt        *time.Time            `json:"finished_at,omitempty"`
	ErrorClass        string                `json:"error_class,omitempty"`
	ErrorMessage      string                `json:"error_message,omitempty"`
	CreatedAt         time.Time             `json:"created_at"`
	UpdatedAt         time.Time             `json:"updated_at"`
}

type TaskBranch struct {
	WorkspaceKey           string    `json:"workspace_key"`
	TaskID                 string    `json:"task_id"`
	RepoName               string    `json:"repo_name"`
	BranchName             string    `json:"branch_name"`
	AdmittedBaseSHA        string    `json:"admitted_base_sha"`
	ExpectedRemoteHeadSHA  string    `json:"expected_remote_head_sha,omitempty"`
	ConfirmedRemoteHeadSHA string    `json:"confirmed_remote_head_sha,omitempty"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
}

type TaskChangePublicationStatus string

const TaskChangePublicationConfirmed TaskChangePublicationStatus = "confirmed"

type TaskChangeSetEntry struct {
	RepoName          string                      `json:"repo_name"`
	BaseSHA           string                      `json:"base_sha"`
	HeadSHA           string                      `json:"head_sha"`
	BranchName        string                      `json:"branch_name"`
	RemoteName        string                      `json:"remote_name"`
	PublicationStatus TaskChangePublicationStatus `json:"publication_status"`
	ArtifactRefs      []string                    `json:"artifact_refs"`
}

type TaskChangeSet struct {
	WorkspaceKey string               `json:"workspace_key"`
	TaskID       string               `json:"task_id"`
	Version      int                  `json:"version"`
	Entries      []TaskChangeSetEntry `json:"entries"`
	CreatedAt    time.Time            `json:"created_at"`
}
