// Code generated by gen-workspace-file-contract from Fleet contracts/workspace-file-v1.json; DO NOT EDIT.
// Source SHA-256: d76f2e909edcce2c036a1c0247e67ad1903033dc8989163e6db67daf44901914

package domain

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"sort"
)

const (
	WorkspaceFileContractSourceSHA256 = "d76f2e909edcce2c036a1c0247e67ad1903033dc8989163e6db67daf44901914"
	MaxWorkspaceFiles                 = 257
	MaxWorkspaceFilePathLength        = 256
	MaxWorkspaceFilePathSegmentLength = 255
	MaxWorkspaceFileBlobRefLength     = 256
	MaxWorkspaceFileMediaTypeLength   = 255
	MaxSkillNameLength                = 64
	MaxSkillDescriptionCharacters     = 1024
	MaxSkillContentBytes              = 100000
	MaxSkillFiles                     = 256
	MaxSkillFilePathLength            = MaxWorkspaceFilePathLength
	MaxSkillFilePathSegmentLength     = MaxWorkspaceFilePathSegmentLength
	MaxSkillFileBytes                 = 131072
	MaxSkillFilesTotalBytes           = 1000000
	MaxSkillProvenanceLength          = 256
)

func WorkspaceFileRevision(file WorkspaceFile) string {
	var encoded workspaceFileCanonicalFields
	encoded.string(file.ContentHash)
	encoded.int64(file.SizeBytes)
	encoded.string(file.MediaType)
	encoded.boolean(file.Executable)
	return "wff1_" + encoded.digest()
}

func WorkspaceFileTreeRevision(files []WorkspaceFile) string {
	canonical := append([]WorkspaceFile(nil), files...)
	sort.Slice(canonical, func(i, j int) bool { return canonical[i].Path < canonical[j].Path })
	var encoded workspaceFileCanonicalFields
	for _, file := range canonical {
		encoded.string(file.Path)
		encoded.string(file.BlobRef)
		encoded.string(file.ContentHash)
		encoded.int64(file.SizeBytes)
		encoded.string(file.MediaType)
		encoded.boolean(file.Executable)
	}
	return "wft1_" + encoded.digest()
}

type workspaceFileCanonicalFields []byte

func (c *workspaceFileCanonicalFields) bytes(value []byte) {
	var length [8]byte
	binary.BigEndian.PutUint64(length[:], uint64(len(value)))
	*c = append(*c, length[:]...)
	*c = append(*c, value...)
}

func (c *workspaceFileCanonicalFields) string(value string) { c.bytes([]byte(value)) }

func (c *workspaceFileCanonicalFields) int64(value int64) {
	var encoded [8]byte
	// #nosec G115 -- two's-complement bits are the canonical int64 encoding.
	binary.BigEndian.PutUint64(encoded[:], uint64(value))
	c.bytes(encoded[:])
}

func (c *workspaceFileCanonicalFields) boolean(value bool) {
	if value {
		c.bytes([]byte{1})
		return
	}
	c.bytes([]byte{0})
}

func (c workspaceFileCanonicalFields) digest() string {
	sum := sha256.Sum256(c)
	return base64.RawURLEncoding.EncodeToString(sum[:])
}
